-- Auto-generated payload defs for RBMS_SOXdebugData2
-- Regenerate: python3 gen_payload_defs.py --message RBMS_SOXdebugData2

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["RBMS_SOXdebugData2"] = {
    total_bytes = 63,
    signals = {
        {
            name = "SaSGPC_CellVmVxT",
            desc = "Equidistant Position Cell Voltage (mV) 等间隔位置的电芯电压 (mV)",
            start_bit = 0,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "1-20",
            array_count = 10,
        },
        {
            name = "ScSOHA_RealSysSOHCPct",
            desc = "Rack Real SOH (%) Rack真实SOH (%)",
            start_bit = 160,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "21-22",
            array_count = 1,
        },
        {
            name = "ScSOHA_DispSysSOHCPct",
            desc = "Rack Display SOH (%) Rack显示SOH (%)",
            start_bit = 176,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "23-24",
            array_count = 1,
        },
        {
            name = "ScSOHA_DFCLCapResultAh",
            desc = "DFCL Module Capacity (Ah) DFCL模块容量 (Ah)",
            start_bit = 192,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "25-26",
            array_count = 1,
        },
        {
            name = "ScSOHA_DFCLPointSOCPct",
            desc = "DFCL Module SOH Feature Point SOC (%) DFCL模块SOH特征点SOC (%)",
            start_bit = 208,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "27-28",
            array_count = 1,
        },
        {
            name = "ScSOHA_DFCLPointStats",
            desc = "DFCL Module SOH Feature Point Status DFCL模块SOH特征点标志位",
            start_bit = 224,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "29",
        },
        {
            name = "ScSOHA_DFCLPointCapAh",
            desc = "DFCL Module SOH Feature Point Capacity (Ah) DFCL模块SOH特征点容量 (Ah)",
            start_bit = 232,
            bit_len = 16,
            res = 0.1,
            off = -1500,
            byte_hint = "30-31",
            array_count = 1,
            signed = true,
        },
        {
            name = "ScSOHA_DFCLPointTimeDay",
            desc = "DFCL Module SOH Feature Point Time (day) DFCL模块SOH特征点时间 (day)",
            start_bit = 248,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "32-33",
            array_count = 1,
        },
        {
            name = "ScSOHA_MFCLCapResultAh",
            desc = "MFCL Module Capacity (Ah) MFCL模块容量 (Ah)",
            start_bit = 264,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "34-35",
            array_count = 1,
        },
        {
            name = "ScSOHA_MFCLTargtValueVmax",
            desc = "Vmax Cell MFCL Module Mid-Feature Point Target Value Vmax节电芯MFCL模块中特征点目标计算值",
            start_bit = 280,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "36-37",
            array_count = 1,
        },
        {
            name = "ScSOHA_MFCLTargtValueVmin",
            desc = "Vmin Cell MFCL Module Mid-Feature Point Target Value Vmin节电芯MFCL模块中特征点目标计算值",
            start_bit = 296,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "38-39",
            array_count = 1,
        },
        {
            name = "SaSOCA_MaxMinSOCPct1",
            desc = "Vmax Cell SOC (%) 最大电压电芯SOC (%)",
            start_bit = 312,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "40-41",
            array_count = 1,
        },
        {
            name = "SaSOCA_MaxMinSOCPct2",
            desc = "Vmin Cell SOC (%) 最小电压电芯SOC (%)",
            start_bit = 328,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "42-43",
            array_count = 1,
        },
        {
            name = "SaSOCA_MaxMinSOCState1",
            desc = "Vmax Cell SOC Status 最大电压电芯SOC状态",
            start_bit = 344,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "44",
        },
        {
            name = "SaSOCA_MaxMinSOCState2",
            desc = "Vmin Cell SOC Status 最小电压电芯SOC状态",
            start_bit = 352,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "45",
        },
        {
            name = "SaSOCA_SimCellVmV1",
            desc = "Vmax Cell Simulation Voltage (mV) 最大电压电芯仿真电压 (mV)",
            start_bit = 360,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "46-47",
            array_count = 1,
        },
        {
            name = "SaSOCA_SimCellVmV2",
            desc = "Vmin Cell Simulation Voltage (mV) 最小电压电芯仿真电压 (mV)",
            start_bit = 376,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "48-49",
            array_count = 1,
        },
        {
            name = "ScSOHA_RealSysCapAh_dbug",
            desc = "Rack Real Capacity (Ah) Rack真实容量 (Ah)",
            start_bit = 392,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "50-51",
            array_count = 1,
        },
        {
            name = "ScSOCA_RealSysSOCPct_dbug",
            desc = "Rack Real SOC (%) Rack真实SOC (%)",
            start_bit = 408,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "52-53",
            array_count = 1,
        },
        {
            name = "ScSOCA_SmthSysSOCPct",
            desc = "Rack Smooth SOC (%) Rack平滑SOC (%)",
            start_bit = 424,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "54-55",
            array_count = 1,
        },
        {
            name = "ScSOCA_DispSysSOCPct",
            desc = "Rack Display SOC (%) Rack显示SOC (%)",
            start_bit = 440,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "56-57",
            array_count = 1,
        },
        {
            name = "ScSOHA_DFCLCalSuccFlg",
            desc = "DFCL Module Capacity Calculation Success Flag DFCL模块容量计算成功标志位",
            start_bit = 456,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLCalSuccFlg",
            desc = "MFCL Module Capacity Calculation Success Flag MFCL模块容量计算成功标志位",
            start_bit = 457,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLPoint1FlgVmax",
            desc = "Vmax Cell MFCL Module Feature Point 1 Vmax节电芯MFCL模块特征点1",
            start_bit = 458,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLPoint1FlgVmin",
            desc = "Vmin Cell MFCL Module Feature Point 1 Vmin节电芯MFCL模块特征点1",
            start_bit = 459,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLPoint2FlgVmax",
            desc = "Vmax Cell MFCL Module Feature Point 2 Vmax节电芯MFCL模块中特征点2",
            start_bit = 460,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLPoint2FlgVmin",
            desc = "Vmin Cell MFCL Module Feature Point 2 Vmin节电芯MFCL模块特征点2",
            start_bit = 461,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLPoint3FlgVmax",
            desc = "Vmax Cell MFCL Module Feature Point 3 Vmax节电芯MFCL模块中特征点3",
            start_bit = 462,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOHA_MFCLPoint3FlgVmin",
            desc = "Vmin Cell MFCL Module Feature Point 3 Vmin节电芯MFCL模块特征点3",
            start_bit = 463,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "58",
        },
        {
            name = "ScSOCA_DispSOCState",
            desc = "DispSOC Follow Strategy Status 显示SOC跟随策略状态",
            start_bit = 464,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "59",
        },
        {
            name = "ScSOCA_TgtSysSOCPct",
            desc = "Rack Target SOC (%) Rack目标SOC (%)",
            start_bit = 472,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "60-61",
            array_count = 1,
        },
        {
            name = "ScSOCA_AccuCapAh",
            desc = "Rack Latest Accu Charge-Discharge Cap (Ah) 最近一次累积充放电容量 (Ah)",
            start_bit = 488,
            bit_len = 16,
            res = 0.1,
            off = -3000,
            byte_hint = "62-63",
            array_count = 1,
        },
    },
}
