-- Auto-generated payload defs for RBMS_SOXdebugData1
-- Regenerate: python3 gen_payload_defs.py --message RBMS_SOXdebugData1

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["RBMS_SOXdebugData1"] = {
    total_bytes = 60,
    signals = {
        {
            name = "ScSGPC_BatIA",
            desc = "Rack Current (A) 簇电流(A)",
            start_bit = 0,
            bit_len = 32,
            res = 0.001,
            off = -2000,
            byte_hint = "1-4",
            array_count = 1,
        },
        {
            name = "ScSGPC_MaxCellVmV",
            desc = "Max Cell Voltage (mV) 最大电芯电压 (mV)",
            start_bit = 32,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "5-6",
            array_count = 1,
        },
        {
            name = "ScSGPC_MinCellVmV",
            desc = "Min Cell Voltage (mV) 最小电芯电压 (mV)",
            start_bit = 48,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "7-8",
            array_count = 1,
        },
        {
            name = "ScSGPC_MaxCellTDegC",
            desc = "Max Cell Temp (℃) 最高电芯温度 (℃)",
            start_bit = 64,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "9-10",
            array_count = 1,
            signed = true,
        },
        {
            name = "ScSGPC_MinCellTDegC",
            desc = "Min Cell Temp (℃) 最低电芯温度 (℃)",
            start_bit = 80,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "11-12",
            array_count = 1,
            signed = true,
        },
        {
            name = "ScSGPC_AvgCellTDegC",
            desc = "Average Cell Temp (℃) 平均电芯温度 (℃)",
            start_bit = 96,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "13-14",
            array_count = 1,
            signed = true,
        },
        {
            name = "ScCSPC_FullChEnaNbr",
            desc = "Full Charge Correction Flag 满充修正标志位",
            start_bit = 112,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "15",
        },
        {
            name = "ScCSPC_FullDischEnaNbr",
            desc = "Full Discharge Correction Flag 满放修正标志位",
            start_bit = 120,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "16",
        },
        {
            name = "ScHIST_HistAccuChCapAh",
            desc = "Accumulated Charge Capacity (Ah) 累计充电容量 (Ah)",
            start_bit = 128,
            bit_len = 32,
            res = 0.0625,
            off = 0,
            byte_hint = "17-20",
            array_count = 1,
        },
        {
            name = "ScHIST_HistAccuDischCapAh",
            desc = "Accumulated Discharge Capacity (Ah) 累计放电容量 (Ah)",
            start_bit = 160,
            bit_len = 32,
            res = 0.0625,
            off = 0,
            byte_hint = "21-24",
            array_count = 1,
        },
        {
            name = "ScSGPC_BatIStNbr",
            desc = "Rack Charging Status Rack充放电状态",
            start_bit = 192,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "25",
        },
        {
            name = "ScSGPC_LstSleepDurTiMin",
            desc = "Last Power-down Sleep Time (min) 上次下电休眠时间",
            start_bit = 200,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "26-29",
            array_count = 1,
        },
        {
            name = "ScSGPC_HisSleepTiMin",
            desc = "History Sleep Time (min) 历史休眠时间",
            start_bit = 232,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "30-33",
            array_count = 1,
        },
        {
            name = "ScSGPC_HisRunTiMin",
            desc = "History Run Time (min) 历史运行时间",
            start_bit = 264,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "34-37",
            array_count = 1,
        },
        {
            name = "ScHIST_CycNbr",
            desc = "Accumulated Cycle Number 累计循环次数",
            start_bit = 296,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "38-39",
            array_count = 1,
        },
        {
            name = "BSWSAllSOHCalIndicator",
            desc = "Rack All SOH Calibration Indicator Rack所有SOH标定指示",
            start_bit = 312,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "40",
        },
        {
            name = "BSWSAllSOHCalValPct",
            desc = "Rack All SOH Calibration Value Rack所有SOH标定值",
            start_bit = 320,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "41",
        },
        {
            name = "ScBTCS_RackChrgCapmAh",
            desc = "Accumulated Charge Capacity (mAh) 累积充电容量 (mAh)",
            start_bit = 328,
            bit_len = 32,
            res = 0.001,
            off = 0,
            byte_hint = "42-45",
            array_count = 1,
        },
        {
            name = "ScBTCS_RackDsChrgCapmAh",
            desc = "Accumulated Discharge Capacity (mAh) 累积放电容量 (mAh)",
            start_bit = 360,
            bit_len = 32,
            res = 0.001,
            off = 0,
            byte_hint = "46-49",
            array_count = 1,
        },
        {
            name = "Reserved",
            desc = "Reserved 预留占位",
            start_bit = 392,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "50",
        },
        {
            name = "Reserved1",
            desc = "Reserved1 预留占位1",
            start_bit = 400,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "51-52",
            array_count = 1,
        },
        {
            name = "BSWSRSOXHistInfoIndicator",
            desc = "Rack History Info Calibration Indicator Rack历史信息标定指示",
            start_bit = 416,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "53",
        },
        {
            name = "BSWSAllSOCCalIndicator",
            desc = "Rack All SOC Calibration Indicator Rack所有SOC标定指示",
            start_bit = 424,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "54",
        },
        {
            name = "BSWSAllSOCCalValPct",
            desc = "Rack All SOC Calibration Value Rack所有SOC标定值",
            start_bit = 432,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "55",
        },
        {
            name = "SbSGPC_BatIVldFlg",
            desc = "Rack Current Validity 簇电流有效性",
            start_bit = 440,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "SbSGPC_GenlCellVVldFlg",
            desc = "Cell Voltage General Validity 电芯电压概要有效性",
            start_bit = 441,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "SbSGPC_GenlCellTVldFlg",
            desc = "Cell Temperature General Validity 电芯温度概要有效性",
            start_bit = 442,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "SbSGPC_MaxCellVMdulTVldFlg",
            desc = "Vmax Cell Temperature Validity 最大电压电芯温度有效性",
            start_bit = 443,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "SbSGPC_MinCellVMdulTVldFlg",
            desc = "Vmin Cell Temperature Validity 最小电压电芯温度有效性",
            start_bit = 444,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "Reserved2",
            desc = "Reserved2 预留占位2",
            start_bit = 445,
            bit_len = 3,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "ScSGPC_MaxCellVMdulTDegC",
            desc = "Vmax Cell Temperature (℃) 最大电压电芯对应温度 (℃)",
            start_bit = 448,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "57-58",
            array_count = 1,
            signed = true,
        },
        {
            name = "ScSGPC_MinCellVMdulTDegC",
            desc = "Vmin Cell Temperature (℃) 最小电压电芯对应温度 (℃)",
            start_bit = 464,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "59-60",
            array_count = 1,
            signed = true,
        },
    },
}
