-- Auto-generated payload defs for BBMS_CtlWord
-- Regenerate: python3 gen_payload_defs.py --message BBMS_CtlWord

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["BBMS_CtlWord"] = {
    total_bytes = 7,
    signals = {
        {
            name = "BBMS_SetCon",
            desc = "Connect/Disconnect String 连接/断开电池串",
            start_bit = 0,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "BBMS_SetEnaIso",
            desc = "Enable/Disable Insulation Measurement  使能/禁止绝缘检测",
            start_bit = 2,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "Reserved",
            desc = "Reserved 预留占位",
            start_bit = 4,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "BBMS_SetEna",
            desc = "Enable/Disable String 使能/禁止电池串",
            start_bit = 6,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "BBMS_Heartbeat",
            desc = "Bank heartbeat Bank 心跳",
            start_bit = 8,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "BBMS_RackEnableFlg",
            desc = "Enable/Disable String After Rack Exit 退簇后使能/禁止电池串",
            start_bit = 16,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "3",
        },
        {
            name = "BBMS_AllowRackExitFlg",
            desc = "Allow Rack Exit System Flag 允许退簇系统标志位",
            start_bit = 24,
            bit_len = 5,
            res = 1,
            off = 0,
            byte_hint = "4",
        },
        {
            name = "BBMS_LocRemCtl",
            desc = "Control Mode 控制模式",
            start_bit = 29,
            bit_len = 3,
            res = 1,
            off = 0,
            byte_hint = "4",
        },
        {
            name = "BBMS_SystemAchitectureNbr",
            desc = "System Architecture Type 系统架构类型",
            start_bit = 32,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "5",
        },
        {
            name = "BBMS_BankFltLvl",
            desc = "Bank Fault Level Bank故障等级",
            start_bit = 36,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "5",
        },
        {
            name = "BBMS_FltSOPDischCoeffPct",
            desc = "Fault-based Discharge Power Limit Coefficient (%) 基于故障的放电功率限制系数",
            start_bit = 40,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "6",
        },
        {
            name = "BBMS_FltSOPChCoeffPct",
            desc = "Fault-based Charge Power Limit Coefficient (%) 基于故障的充电功率限制系数",
            start_bit = 48,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "7",
        },
    },
}
