-- Auto-generated payload defs for RBMS_Debug
-- Regenerate: python3 gen_payload_defs.py --message RBMS_Debug

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["RBMS_Debug"] = {
    total_bytes = 30,
    signals = {
        {
            name = "SbCTSC_AllwPrechFlg",
            desc = "Allow to Precharge Flag 允许预充标志位",
            start_bit = 0,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "SbCTSC_BSWSMainNegRlyDryContactFlg",
            desc = "Main Negative Contactor Status 主负继电器干接点状态",
            start_bit = 1,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "SbCTSC_BSWSMainPosRlyDryContactFlg",
            desc = "Main Positive Contactor Status 主正继电器干接点状态",
            start_bit = 2,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "SbCTSC_SafetyState3TriggerFlg",
            desc = "High-voltage indicator in safe state 3 安全状态3下高压标志",
            start_bit = 3,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "Reserved",
            desc = "Reserved 预留占位",
            start_bit = 4,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "ScCTSC_HvPowupCmdNbr",
            desc = "Hv Power-on Mode 上高压模式",
            start_bit = 8,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "ScCTSC_CtrlModeState",
            desc = "Control Mode Status 控制模式状态",
            start_bit = 16,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "3",
        },
        {
            name = "ScCTSC_MainPosRlyLsdDrvRawVoltV",
            desc = "Main positive relay low-side drive voltage (V) 主正低边驱动电压 (V)",
            start_bit = 24,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "4-5",
            array_count = 1,
        },
        {
            name = "ScCTSC_MainNegRlyLsdDrvRawVoltV",
            desc = "Main negative relay low-side drive voltage (V) 主负低边驱动电压 (V)",
            start_bit = 40,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "6-7",
            array_count = 1,
        },
        {
            name = "ScCTSC_GroundChannelRawVoltmV",
            desc = "Grounding channel voltage (mV) 接地通道电压 (mV)",
            start_bit = 56,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "8-9",
            array_count = 1,
        },
        {
            name = "ScCTSC_MainPosRlyHsdDrvRawCurmA",
            desc = "Main positive relay high-side drive current (mA) 主正高边驱动电流 (mA)",
            start_bit = 72,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "10-11",
            array_count = 1,
        },
        {
            name = "ScCTSC_PrechRlyHsdDrvRawCurmA",
            desc = "High-side drive current of the pre-charging relay (mA) 预充高边驱动电流 (mA)",
            start_bit = 88,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "12-13",
            array_count = 1,
        },
        {
            name = "ScCTSC_MainNegRlyHsdDrvRawCurmA",
            desc = "Main negative relay high-side drive current (mA) 主负高边驱动电流 (mA)",
            start_bit = 104,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "14-15",
            array_count = 1,
        },
        {
            name = "ScCTSC_PrechOverTiCnt",
            desc = "Number of consecutive precharge timeout occurrences 连续预充超时次数",
            start_bit = 120,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "16",
        },
        {
            name = "ScBTCS_BSWSBatIDiagInfoNbr",
            desc = "Current Sensor Hardware Flt 电流传感器硬件诊断信息",
            start_bit = 128,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "17",
        },
        {
            name = "ScBTCS_BSWSMsgAvlNbr",
            desc = "Current Sensor Msg Timeout Flt 电流传感器报文超时故障",
            start_bit = 130,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "17",
        },
        {
            name = "SbLVPH_CurrSnsrPowSplyNotOutRngFlg",
            desc = "Current Sensor Power Supply Volt Out Range Flg 电流传感器供电电压超上下限标志",
            start_bit = 132,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "17",
        },
        {
            name = "SbCTSC_RlyLoadBreakFlg",
            desc = "Contactor Off-with-Load Flg 继电器带载断开标志位",
            start_bit = 133,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "17",
        },
        {
            name = "Reserved1",
            desc = "Reserved1 预留占位1",
            start_bit = 134,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "17",
        },
        {
            name = "ScCTSC_RlyLoadBreakCurrentA",
            desc = "Current when Contactor Off-with-Load (A) 继电器带载断开时的电池串电流 (A)",
            start_bit = 136,
            bit_len = 32,
            res = 0.001,
            off = -2000,
            byte_hint = "18-21",
            array_count = 1,
        },
        {
            name = "ScBTCS_BSWSMsgCtrResNbr",
            desc = "Current Sensor Msg Rolling Counter Flt 电流传感器报文RollingCounter故障",
            start_bit = 168,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "22",
        },
        {
            name = "ScBTCS_BSWSMsgCRCResNbr",
            desc = "Current Sensor Msg CRC Flt 电流传感器报文CRC故障",
            start_bit = 170,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "22",
        },
        {
            name = "ScBTCS_BSWSCurValVldNbr",
            desc = "Current Sensor Current Value Invalid 电流传感器电流值无效",
            start_bit = 172,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "22",
        },
        {
            name = "ScBTCS_CANBatIZeroDriftNbr",
            desc = "Current Sensor Zero Drift 电流传感器零漂",
            start_bit = 174,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "22",
        },
        {
            name = "BSWSAFESampErrMonitor",
            desc = "BSW AFE Sampling Error Monitor 底层AFE采样错误监测",
            start_bit = 176,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "23-26",
            array_count = 1,
        },
        {
            name = "BSWEthPHYChipResetNbr",
            desc = "BSW Ethernet PHY Chip Reset Number (RBMS) 以太网PHY芯片复位次数",
            start_bit = 208,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "27-30",
            array_count = 1,
        },
    },
}
