-- Auto-generated payload defs for HMI_BBMSDOCtrl
-- Regenerate: python3 gen_payload_defs.py --message HMI_BBMSDOCtrl

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["HMI_BBMSDOCtrl"] = {
    total_bytes = 2,
    signals = {
        {
            name = "HMI_BBMSDO0CtrlFlg",
            desc = "DO0 DO0控制",
            start_bit = 0,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO1CtrlFlg",
            desc = "DO1 DO1控制",
            start_bit = 1,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO2CtrlFlg",
            desc = "DO2 DO2控制",
            start_bit = 2,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO3CtrlFlg",
            desc = "DO3 DO3控制",
            start_bit = 3,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO4CtrlFlg",
            desc = "DO4 DO4控制",
            start_bit = 4,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO5CtrlFlg",
            desc = "DO5 DO5控制",
            start_bit = 5,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO6CtrlFlg",
            desc = "DO6 DO6控制",
            start_bit = 6,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO7CtrlFlg",
            desc = "DO7 DO7控制",
            start_bit = 7,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_BBMSDO8CtrlFlg",
            desc = "DO8 DO8控制",
            start_bit = 8,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_BBMSDO9CtrlFlg",
            desc = "DO9 DO9控制",
            start_bit = 9,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_BBMSDO10CtrlFlg",
            desc = "DO10 DO10控制",
            start_bit = 10,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_BBMSDO11CtrlFlg",
            desc = "DO11 DO11控制",
            start_bit = 11,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
    },
}
