-- Auto-generated payload defs for TMS_SumInfo
-- Regenerate: python3 gen_payload_defs.py --message TMS_SumInfo

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["TMS_SumInfo"] = {
    total_bytes = 12,
    signals = {
        {
            name = "BBMS_WtrTmpCmd",
            desc = "Setting Temp (℃) 设定温度(℃)",
            start_bit = 0,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "1",
        },
        {
            name = "BBMS_cellTmpMax",
            desc = "Max Cell Temp (℃) 电芯最高温度(℃)",
            start_bit = 8,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "2",
        },
        {
            name = "BBMS_cellTmpMin",
            desc = "Min Cell Temp (℃) 电芯最低温度(℃)",
            start_bit = 16,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "3",
        },
        {
            name = "BBMS_cellTmpAvg",
            desc = "Average Cell Temp (℃) 电芯平均温度(℃)",
            start_bit = 24,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "4",
        },
        {
            name = "TMS_OutWtrTmp",
            desc = "Outlet Water Temp (℃) 出水温度(℃)",
            start_bit = 32,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "5",
        },
        {
            name = "TMS_BackWtrTmp",
            desc = "Inlet Water Temp (℃) 进水温度(℃)",
            start_bit = 40,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "6",
        },
        {
            name = "TMS_EnvTmp",
            desc = "Environment Temp (℃) 环境温度(℃)",
            start_bit = 48,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "7",
        },
        {
            name = "TMS_InWtrP",
            desc = "Inlet Water Pressure (Bar) 进水水压(Bar)",
            start_bit = 56,
            bit_len = 8,
            res = 0.1,
            off = 0,
            byte_hint = "8",
        },
        {
            name = "TMS_OutWtrP",
            desc = "Outlet Water Pressure  (Bar) 出水水压(Bar)",
            start_bit = 64,
            bit_len = 8,
            res = 0.1,
            off = 0,
            byte_hint = "9",
        },
        {
            name = "TMS_BBMSFltLevel",
            desc = "TMS Fault Level TMS 故障等级",
            start_bit = 72,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "10",
        },
        {
            name = "TMS_BBMSFltCode",
            desc = "TMS Fault Code TMS 故障码",
            start_bit = 74,
            bit_len = 6,
            res = 1,
            off = 0,
            byte_hint = "10",
        },
        {
            name = "BMS_TMSReqMode",
            desc = "BMS Request Mode BMS请求模式",
            start_bit = 80,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "11",
        },
        {
            name = "TMS_BMSMode",
            desc = "TMS Working Mode TMS工作模式",
            start_bit = 82,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "11",
        },
        {
            name = "TMSNo",
            desc = "TMS Number TMS编号",
            start_bit = 84,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "11",
        },
        {
            name = "TMSCoolState",
            desc = "TMS Cool Status TMS制冷状态",
            start_bit = 88,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "12",
        },
    },
}
