-- Auto-generated payload defs for ParaThr_RackV
-- Regenerate: python3 gen_payload_defs.py --message ParaThr_RackV

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["ParaThr_RackV"] = {
    total_bytes = 20,
    signals = {
        {
            name = "CcHVSH_BatOVLvl1FltCfmThdV",
            desc = "BatOVLvl1FltCfmThdV 电池串过压一级报警阈值",
            start_bit = 0,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "1-2",
        },
        {
            name = "CcHVSH_BatOVLvl2FltCfmThdV",
            desc = "BatOVLvl2FltCfmThdV 电池串过压二级报警阈值",
            start_bit = 16,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "3-4",
        },
        {
            name = "CcHVSH_BatOVLvl2FltRcvrThdV",
            desc = "BatOVLvl2FltRcvrThdV 电池串过压二级恢复阈值",
            start_bit = 32,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "5-6",
        },
        {
            name = "CcHVSH_BatOVLvl3FltCfmThdV",
            desc = "BatOVLvl3FltCfmThdV 电池串过压三级报警阈值",
            start_bit = 48,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "7-8",
        },
        {
            name = "CcHVSH_BatOVLvl3FltRcvrThdV",
            desc = "BatOVLvl3FltRcvrThdV 电池串过压三级恢复阈值",
            start_bit = 64,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "9-10",
        },
        {
            name = "CcHVSH_BatUVLvl1FltCfmThdV",
            desc = "BatUVLvl1FltCfmThdV 电池串欠压一级报警阈值",
            start_bit = 80,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "11-12",
        },
        {
            name = "CcHVSH_BatUVLvl2FltCfmThdV",
            desc = "BatUVLvl2FltCfmThdV 电池串欠压二级报警阈值",
            start_bit = 96,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "13-14",
        },
        {
            name = "CcHVSH_BatUVLvl2FltRcvrThdV",
            desc = "BatUVLvl2FltRcvrThdV 电池串欠压二级恢复阈值",
            start_bit = 112,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "15-16",
        },
        {
            name = "CcHVSH_BatUVLvl3FltCfmThdV",
            desc = "BatUVLvl3FltCfmThdV 电池串欠压三级报警阈值",
            start_bit = 128,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "17-18",
        },
        {
            name = "CcHVSH_BatUVLvl3FltRcvrThdV",
            desc = "BatUVLvl3FltRcvrThdV 电池串欠压三级恢复阈值",
            start_bit = 144,
            bit_len = 16,
            res = 0.001,
            off = 0,
            byte_hint = "19-20",
        },
    },
}
