-- Auto-generated payload defs for HMI_RBMSDOCtrl
-- Regenerate: python3 gen_payload_defs.py --message HMI_RBMSDOCtrl

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["HMI_RBMSDOCtrl"] = {
    total_bytes = 2,
    signals = {
        {
            name = "HMI_RBMSDO1HCtrlFlg",
            desc = "DO1H DO1高边控制",
            start_bit = 0,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO1LCtrlFlg",
            desc = "DO1L DO1低边控制",
            start_bit = 1,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO2HCtrlFlg",
            desc = "DO2H DO2高边控制",
            start_bit = 2,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO2LCtrlFlg",
            desc = "DO2L DO2低边控制",
            start_bit = 3,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO3HCtrlFlg",
            desc = "DO3H DO3高边控制",
            start_bit = 4,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO3LCtrlFlg",
            desc = "DO3L DO3低边控制",
            start_bit = 5,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO4HCtrlFlg",
            desc = "DO4H DO4高边控制",
            start_bit = 6,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO4LCtrlFlg",
            desc = "DO4L DO4低边控制",
            start_bit = 7,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RBMSDO5LCtrlFlg",
            desc = "DO5L DO5低边控制",
            start_bit = 8,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_RBMSDO6LCtrlFlg",
            desc = "DO6L DO6低边控制",
            start_bit = 9,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_RBMSDO7CtrlFlg",
            desc = "DO7 DO7控制",
            start_bit = 10,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_RBMSDO8CtrlFlg",
            desc = "DO8 DO8控制",
            start_bit = 11,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
    },
}
