-- Auto-generated payload def loader manifest
-- Regenerate: python3 gen_payload_defs.py --default-set

return {
    "bms20_payload_RBMS_SumInfo.lua",
    "bms20_payload_RBMS_Volt.lua",
    "bms20_payload_RBMS_Temp.lua",
    "bms20_payload_RBMS_CellBalSt.lua",
    "bms20_payload_RBMS_CellSdr.lua",
    "bms20_payload_BBMS_SumInfo.lua",
    "bms20_payload_BBMS_CtlWord.lua",
    "bms20_payload_HMI_CtlWord.lua",
    "bms20_payload_HMI_TMSCtrlWord.lua",
    "bms20_payload_HMI_BankDOCtrl.lua",
    "bms20_payload_HMI_RackCaliCtrl.lua",
    "bms20_payload_HMI_RBMSRlyCtrl.lua",
    "bms20_payload_TMS_SumInfo.lua",
    "bms20_payload_ParaThr_CellV.lua",
    "bms20_payload_ParaThr_RackV.lua",
    "bms20_payload_ParaThr_RackI.lua",
    "bms20_payload_ParaThr_ModuleT.lua",
    "bms20_payload_ParaThr_SOX.lua",
    "bms20_payload_ParaThr_AUX.lua",
    "bms20_payload_ParaThr_TMS.lua",
    "bms20_payload_HMI_RBMSDOCtrl.lua",
    "bms20_payload_HMI_BBMSDOCtrl.lua",
    "bms20_payload_RBMS_SOXdebugData1.lua",
    "bms20_payload_RBMS_SOXdebugData2.lua",
    "bms20_payload_HMI_RackFaultCali.lua",
    "bms20_payload_HMI_BankFaultCali.lua",
    "bms20_payload_HMI_FltOvTiNbr.lua",
    "bms20_payload_RBMS_Debug.lua",
    "bms20_payload_BBMS_A_SOCInfo.lua",
    "bms20_payload_BBMS_A_SOHInfo.lua",
    "bms20_payload_HMI_FltEna.lua",
    "bms20_payload_BBMS_A_Selfdr.lua",
    "bms20_payload_BBMS_SafetySignal.lua",
    "bms20_payload_BBMS_A_CtlWord.lua",
}
