-- Auto-generated payload defs for HMI_CtlWord
-- Regenerate: python3 gen_payload_defs.py --message HMI_CtlWord

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["HMI_CtlWord"] = {
    total_bytes = 7,
    signals = {
        {
            name = "HMI_AlmRst",
            desc = "Alarm Reset 清除所有故障信息",
            start_bit = 0,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_SetEnaIso",
            desc = "Enable/Disable Insulation Measurement  使能/禁止绝缘检测",
            start_bit = 2,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "Reserved",
            desc = "Reserved 预留占位",
            start_bit = 4,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_SetEna",
            desc = "Enable/Disable String (RBMS) 使能/禁止电池串",
            start_bit = 6,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_EPORst",
            desc = "EPO Reset 清除所有EPO",
            start_bit = 8,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_EnaIsoManualCtrl",
            desc = "Enable/Disable Insulation Measurement Manual Control (RBMS) 手动控制使能/禁止绝缘检测",
            start_bit = 10,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_SetCon",
            desc = "Connect/Disconnect String (RBMS) 连接/断开电池串",
            start_bit = 12,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "HMI_IDLearnManualCtrl",
            desc = "Manually Control Bank Executing ID Learn 手动控制Bank执行ID编码",
            start_bit = 16,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "3",
        },
        {
            name = "HMI_AutoHvUpConf",
            desc = "Auto Hv up configuration 自动上高压设置",
            start_bit = 24,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "4",
        },
        {
            name = "HMI_IDLearnDoCtrl",
            desc = "ID Learn DO Control 自动编码DO输出控制",
            start_bit = 32,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "5",
        },
        {
            name = "HMI_PmtRkFltNum",
            desc = "Min number of Racks Allowed to Run 允许运行的最小Rack数量",
            start_bit = 40,
            bit_len = 6,
            res = 1,
            off = 0,
            byte_hint = "6",
        },
        {
            name = "HMI_PCSComDiagConf",
            desc = "PCS Communication Diagnosis Configuration PCS 通讯诊断设置",
            start_bit = 46,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "6",
        },
        {
            name = "HMI_LocRemCtl",
            desc = "Control Mode 控制模式",
            start_bit = 48,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "7",
        },
        {
            name = "BBMSNo",
            desc = "Bank Number 堆编号",
            start_bit = 52,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "7",
        },
    },
}
