-- Auto-generated payload defs for BBMS_SumInfo
-- Regenerate: python3 gen_payload_defs.py --message BBMS_SumInfo

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["BBMS_SumInfo"] = {
    total_bytes = 130,
    signals = {
        {
            name = "BBMS_BatSt",
            desc = "Bank Status Bank工作状态",
            start_bit = 0,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "BBMS_ChSt",
            desc = "Bank Charging Status Bank充放电状态",
            start_bit = 8,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "BBMS_SysOperSt",
            desc = "Bank System Operating Status Bank系统运行状态",
            start_bit = 16,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "3-4",
        },
        {
            name = "BBMS_PmtRkFltNum",
            desc = "Min number of Racks Allowed to Run 允许运行的最小Rack数量",
            start_bit = 32,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "5-6",
        },
        {
            name = "BBMS_SetInverterSt",
            desc = "Set Inverter Status 设置逆变器状态",
            start_bit = 48,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "7",
        },
        {
            name = "BBMS_RackFltLvl1Nbr",
            desc = "Positions of Rack with Emergency Fault  存在严重故障的Rack位置",
            start_bit = 56,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "8-9",
        },
        {
            name = "BBMS_CntrSt",
            desc = "Bank Contactor Status Bank接触器状态",
            start_bit = 72,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "10-11",
        },
        {
            name = "BBMS_SOC",
            desc = "System SOC (%)  系统SOC (%)",
            start_bit = 88,
            bit_len = 8,
            res = 0.5,
            off = 0,
            byte_hint = "12",
        },
        {
            name = "BBMS_SOH",
            desc = "System SOH (%)  系统SOH (%)",
            start_bit = 96,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "13",
        },
        {
            name = "BBMS_MaxChrgE",
            desc = "SOE for Charge (kWh)  系统可充能量 (kWh)",
            start_bit = 104,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "14-15",
        },
        {
            name = "BBMS_MaxDisChrgE",
            desc = "SOE for Discharge (kWh)  系统可放能量 (kWh)",
            start_bit = 120,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "16-17",
        },
        {
            name = "BBMS_MaxContChrgPower",
            desc = "Const Charge Power Limit (kW)  持续充电功率限制 (kW)",
            start_bit = 136,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "18-19",
        },
        {
            name = "BBMS_Max60sChrgPower",
            desc = "Pulse Charge Power Limit (kW)  脉冲充电功率限制 (kW)",
            start_bit = 152,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "20-21",
        },
        {
            name = "BBMS_MaxContDisChrgPower",
            desc = "Const Discharge Power Limit (kW)  持续放电功率限制 (kW)",
            start_bit = 168,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "22-23",
        },
        {
            name = "BBMS_Max60sDisChrgPower",
            desc = "Pulse Discharge Power Limit (kW)  脉冲放电功率限制 (kW)",
            start_bit = 184,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "24-25",
        },
        {
            name = "BBMS_MaxContChrgCur",
            desc = "Const Charge Curr Limit (A)  持续充电电流限制 (A)",
            start_bit = 200,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "26-27",
        },
        {
            name = "BBMS_Max60sChrgCur",
            desc = "Pulse Charge Curr Limit (A)  脉冲充电电流限制 (A)",
            start_bit = 216,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "28-29",
        },
        {
            name = "BBMS_MaxContDisChrgCur",
            desc = "Const Discharge Curr Limit (A)  持续放电电流限制 (A)",
            start_bit = 232,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "30-31",
        },
        {
            name = "BBMS_Max60sDisChrgCur",
            desc = "Pulse Discharge Curr Limit (A)  脉冲放电电流限制 (A)",
            start_bit = 248,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "32-33",
        },
        {
            name = "BBMS_HumSensorRH",
            desc = "Bank Humidity (RH)  Bank湿度 (RH)",
            start_bit = 264,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "34-35",
        },
        {
            name = "BBMS_TmpSensorRH",
            desc = "Bank Temp (℃)  Bank温度 (℃)",
            start_bit = 280,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "36-37",
            signed = true,
        },
        {
            name = "BBMS_WtrSt",
            desc = "Bank Water Sensor Status  Bank水浸状态",
            start_bit = 296,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "38",
        },
        {
            name = "BBMS_StrCtrlHb",
            desc = "Bank BMS Heartbeat Bank BMS心跳信号",
            start_bit = 304,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "39-40",
        },
        {
            name = "BBMS_DCBusV",
            desc = "DC Bus Voltage (V) 母线电压 (V)",
            start_bit = 320,
            bit_len = 16,
            res = 0.5,
            off = 0,
            byte_hint = "41-42",
        },
        {
            name = "BBMS_TotalDCCur",
            desc = "DC Bus Current (A) 母线电流 (A)",
            start_bit = 336,
            bit_len = 16,
            res = 0.125,
            off = -4000,
            byte_hint = "43-44",
            signed = true,
        },
        {
            name = "BBMS_TotalPower",
            desc = "Total Power (kW) 总功率 (kW)",
            start_bit = 352,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "45-46",
        },
        {
            name = "BBMS_MaxRackCur",
            desc = "Max Rack Current (A) 最大Rack电流 (A)",
            start_bit = 368,
            bit_len = 16,
            res = 0.125,
            off = -2000,
            byte_hint = "47-48",
            signed = true,
        },
        {
            name = "BBMS_MaxCurRackNr",
            desc = "Max Current Rack Position 最大电流Rack位置",
            start_bit = 384,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "49",
        },
        {
            name = "BBMS_MinRackCur",
            desc = "Min Rack Current (A) 最小Rack电流 (A)",
            start_bit = 392,
            bit_len = 16,
            res = 0.125,
            off = -2000,
            byte_hint = "50-51",
            signed = true,
        },
        {
            name = "BBMS_MinCurRackNr",
            desc = "Min Current Rack Position 最小电流Rack位置",
            start_bit = 408,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "52",
        },
        {
            name = "BBMS_MaxCellV",
            desc = "Max Cell Voltage (mV) 最大电芯电压 (mV)",
            start_bit = 416,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "53-54",
        },
        {
            name = "BBMS_MaxVCellRackNr",
            desc = "Max Cell Voltage Rack Position 最大电芯电压Rack位置",
            start_bit = 432,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "55",
        },
        {
            name = "BBMS_MaxVCellTrayNr",
            desc = "Max Cell Voltage Module Position 最大电芯电压模组位置",
            start_bit = 440,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "56",
        },
        {
            name = "BBMS_MaxVCellNr",
            desc = "Max Cell Voltage Module Inner Position 最大电芯电压模组内位置",
            start_bit = 448,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "57",
        },
        {
            name = "BBMS_MinCellV",
            desc = "Min Cell Voltage (mV) 最小电芯电压 (mV)",
            start_bit = 456,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "58-59",
        },
        {
            name = "BBMS_MinVCellRackNr",
            desc = "Min Cell Voltage Rack Position 最小电芯电压Rack位置",
            start_bit = 472,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "60",
        },
        {
            name = "BBMS_MinVCellTrayNr",
            desc = "Min Cell Voltage Module Position 最小电芯电压模组位置",
            start_bit = 480,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "61",
        },
        {
            name = "BBMS_MinVCellNr",
            desc = "Min Cell Voltage Position 最小电芯电压模组内位置",
            start_bit = 488,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "62",
        },
        {
            name = "BBMS_AvgCellV",
            desc = "Average Cell Voltage (mV) 平均电芯电压 (mV)",
            start_bit = 496,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "63-64",
        },
        {
            name = "BBMS_MaxHvBoxTRackNr",
            desc = "Max Hv Box Temp Rack Position 最高高压箱温度Rack位置",
            start_bit = 512,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "65",
        },
        {
            name = "BBMS_MaxTCellRackNr",
            desc = "Max Cell Temp Rack Position 最高电芯温度Rack位置",
            start_bit = 520,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "66",
        },
        {
            name = "BBMS_MaxTCellTrayNr",
            desc = "Max Cell Temp Module Position 最高电芯温度模组位置",
            start_bit = 528,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "67",
        },
        {
            name = "BBMS_MaxTCellNr",
            desc = "Max Cell Temp Module Inner Position  最高电芯温度模组内位置",
            start_bit = 536,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "68",
        },
        {
            name = "BBMS_MinHvBoxTRackNr",
            desc = "Min Hv Box Temp Rack Position 最低高压箱温度Rack位置",
            start_bit = 544,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "69",
        },
        {
            name = "BBMS_MinTCellRackNr",
            desc = "Min Cell Temp Rack Position 最低电芯温度Rack位置",
            start_bit = 552,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "70",
        },
        {
            name = "BBMS_MinTCellTrayNr",
            desc = "Min Cell Temp Module Position 最低电芯温度模组位置",
            start_bit = 560,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "71",
        },
        {
            name = "BBMS_MinTCellNr",
            desc = "Min Cell Temp Module Inner Position  最低电芯温度模组内位置",
            start_bit = 568,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "72",
        },
        {
            name = "BBMS_ProhUpgradeFlg",
            desc = "Prohibited Upgrade Flag 禁止升级标志位",
            start_bit = 576,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "73",
        },
        {
            name = "BBMS_BMSMaxFltLevel",
            desc = "System Fault Level 系统故障等级",
            start_bit = 584,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "74",
        },
        {
            name = "BBMS_IDLearnSt",
            desc = "Bank ID Learn Status  Bank ID编码状态",
            start_bit = 592,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "75",
        },
        {
            name = "BBMS_IDLearnFaiLocationNbr",
            desc = "Bank ID Learn Fail Position Bank ID编码失败位置",
            start_bit = 600,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "76",
        },
        {
            name = "BBMS_IsoRPos",
            desc = "Positive to GND Insulation Resistance (kOhm) 正对地绝缘阻值 (kOhm)",
            start_bit = 608,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "77-78",
        },
        {
            name = "BBMS_IsoRNeg",
            desc = "Negative to GND Insulation Resistance (kOhm) 负对地绝缘阻值 (kOhm)",
            start_bit = 624,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "79-80",
        },
        {
            name = "BBMS_AccuChrgC",
            desc = "Accu Charge Cap (Ah) 累计充电容量 (Ah)",
            start_bit = 640,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "81-84",
        },
        {
            name = "BBMS_AccuChrgE",
            desc = "Accu Charge Eng (kWh) 累计充电能量 (kWh)",
            start_bit = 672,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "85-88",
        },
        {
            name = "BBMS_AccuDisChrgC",
            desc = "Accu Discharge Cap (Ah) 累计放电容量 (Ah)",
            start_bit = 704,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "89-92",
        },
        {
            name = "BBMS_AccuDisChrgE",
            desc = "Accu Discharge Eng (kWh) 累计放电能量 (kWh)",
            start_bit = 736,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "93-96",
        },
        {
            name = "BBMS_LstChEkWh",
            desc = "Bank Last Charge Energy (kWh) 最近一次堆充电能量 (kWh)",
            start_bit = 768,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "97-98",
        },
        {
            name = "BBMS_LstDchEkWh",
            desc = "Bank Last Discharge Energy (kWh) 最近一次堆放电能量 (kWh)",
            start_bit = 784,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "99-100",
        },
        {
            name = "BBMS_RackEnaNbr",
            desc = "Rack Enable Number Rack使能数量",
            start_bit = 800,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "101",
        },
        {
            name = "BBMS_RackOnlineNbr",
            desc = "Rack Online Number Rack在线数量",
            start_bit = 808,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "102",
        },
        {
            name = "BBMS_ConFail",
            desc = "HV Connect Fail Reason 高压连接失败原因",
            start_bit = 816,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "103",
        },
        {
            name = "BBMS_MaxChrgCap",
            desc = "Remaining Charge Cap (Ah) 可充容量 (Ah)",
            start_bit = 824,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "104-105",
        },
        {
            name = "BBMS_MaxDisChrgCap",
            desc = "Remaining Discharge Cap (Ah) 可放容量 (Ah)",
            start_bit = 840,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "106-107",
        },
        {
            name = "BBMS_MaxHvBoxTDegC",
            desc = "Max Hv Box Temp (℃) 最高高压箱温度 (℃)",
            start_bit = 856,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "108-109",
            signed = true,
        },
        {
            name = "BBMS_MinHvBoxTDegC",
            desc = "Min Hv Box Temp (℃) 最低高压箱温度 (℃)",
            start_bit = 872,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "110-111",
            signed = true,
        },
        {
            name = "BBMS_MaxCellT",
            desc = "Max Cell Temp (℃)  最高电芯温度 (℃)",
            start_bit = 888,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "112-113",
            signed = true,
        },
        {
            name = "BBMS_MinCellT",
            desc = "Min Cell Temp (℃)  最低电芯温度 (℃)",
            start_bit = 904,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "114-115",
            signed = true,
        },
        {
            name = "BBMS_AvgCellT",
            desc = "Average Cell Temp (℃)  平均电芯温度 (℃)",
            start_bit = 920,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "116-117",
            signed = true,
        },
        {
            name = "BBMS_MaxPoleT",
            desc = "Max Pole Temp (℃) 最高极柱温度 (℃)",
            start_bit = 936,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "118-119",
            signed = true,
        },
        {
            name = "BBMS_MinPoleT",
            desc = "Min Pole Temp (℃) 最低极柱温度 (℃)",
            start_bit = 952,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "120-121",
            signed = true,
        },
        {
            name = "BBMS_MaxPoleTRackNr",
            desc = "Max Pole Temp Rack Position 最高极柱温度Rack位置",
            start_bit = 968,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "122",
        },
        {
            name = "BBMS_MaxPoleTMdulNr",
            desc = "Max Pole Temp Module Position 最高极柱温度模组位置",
            start_bit = 976,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "123",
        },
        {
            name = "BBMS_MaxPoleTMdulInnerNr",
            desc = "Max Pole Temp Module Inner Position  最高极柱温度模组内位置",
            start_bit = 984,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "124",
        },
        {
            name = "BBMS_MinPoleTRackNr",
            desc = "Min Pole Temp Rack Position 最低极柱温度Rack位置",
            start_bit = 992,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "125",
        },
        {
            name = "BBMS_MinPoleTMdulNr",
            desc = "Min Pole Temp Module Position 最低极柱温度模组位置",
            start_bit = 1000,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "126",
        },
        {
            name = "BBMS_MinPoleTMdulInnerNr",
            desc = "Min Pole Temp Module Inner Position  最低极柱温度模组内位置",
            start_bit = 1008,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "127",
        },
        {
            name = "BBMSNo",
            desc = "Bank Number 堆编号",
            start_bit = 1016,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "128",
        },
        {
            name = "BBMS_StartReConDectFlg",
            desc = "Rack Anti-Reverse Connection Detection Start Flag 簇防反接检测开始标志位",
            start_bit = 1020,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "128",
        },
        {
            name = "Reserved",
            desc = "Reserved 预留占位",
            start_bit = 1021,
            bit_len = 3,
            res = 1,
            off = 0,
            byte_hint = "128",
        },
        {
            name = "BBMS_ReverConRackFailNbr",
            desc = "HV Box And Busbar Cabinet reverse connection cluster 高压盒与汇流柜反接簇编号",
            start_bit = 1024,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "129-130",
        },
    },
}
