-- Auto-generated payload defs for ParaThr_CellV
-- Regenerate: python3 gen_payload_defs.py --message ParaThr_CellV

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["ParaThr_CellV"] = {
    total_bytes = 36,
    signals = {
        {
            name = "CcCLVH_MaxCellVOvLvl1FltVmV",
            desc = "MaxCellVOvLvl1FltVmV 单体过压一级报警阈值",
            start_bit = 0,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "1-2",
        },
        {
            name = "FULL_CHARGE_CELLV",
            desc = "MaxCellVOvLvl2FltVmV 单体过压二级报警阈值",
            start_bit = 16,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "3-4",
        },
        {
            name = "CcCLVH_MaxCellVOvLvl2FltRcvryVmV",
            desc = "MaxCellVOvLvl2FltRcvryVmV 单体过压二级恢复阈值",
            start_bit = 32,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "5-6",
        },
        {
            name = "CcCLVH_MaxCellVOvLvl3FltVmV",
            desc = "MaxCellVOvLvl3FltVmV 单体过压三级报警阈值",
            start_bit = 48,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "7-8",
        },
        {
            name = "CcCLVH_MaxCellVOvLvl3FltRcvryVmV",
            desc = "MaxCellVOvLvl3FltRcvryVmV 单体过压三级恢复阈值",
            start_bit = 64,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "9-10",
        },
        {
            name = "CcCLVH_MaxCellVOvLvl4FltVmV",
            desc = "MaxCellVOvLvl4FltVmV 单体过压极限报警阈值",
            start_bit = 80,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "11-12",
        },
        {
            name = "CcCLVH_MinCellVUvLvl1FltVmV",
            desc = "MinCellVUvLvl1FltVmV 单体欠压一级报警阈值",
            start_bit = 96,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "13-14",
        },
        {
            name = "FULL_DISCHARGE_CELLV",
            desc = "MinCellVUvLvl2FltVmV 单体欠压二级报警阈值",
            start_bit = 112,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "15-16",
        },
        {
            name = "CcCLVH_MinCellVUvLvl2FltRcvryVmV",
            desc = "MinCellVUvLvl2FltRcvryVmV 单体欠压二级恢复阈值",
            start_bit = 128,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "17-18",
        },
        {
            name = "CcCLVH_MinCellVUvLvl3FltVmV",
            desc = "MinCellVUvLvl3FltVmV 单体欠压三级报警阈值",
            start_bit = 144,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "19-20",
        },
        {
            name = "CcCLVH_MinCellVUvLvl3FltRcvryVmV",
            desc = "MinCellVUvLvl3FltRcvryVmV 单体欠压三级恢复阈值",
            start_bit = 160,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "21-22",
        },
        {
            name = "CcCLVH_MinCellVUvLvl4FltV1mV",
            desc = "MinCellVUvLTLvl4FltVmV 低温单体欠压极限报警阈值",
            start_bit = 176,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "23-24",
        },
        {
            name = "CcCLVH_MinCellVUvLvl4FltV2mV",
            desc = "MinCellVUvHTLvl4FltVmV 常温单体欠压极限报警阈值",
            start_bit = 192,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "25-26",
        },
        {
            name = "CcCLVH_DeltaCellVOLLvl1FltVmV",
            desc = "DeltaCellVOLLvl1FltVmV 单体压差过大一级报警阈值",
            start_bit = 208,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "27-28",
        },
        {
            name = "CcCLVH_DeltaCellVOLLvl2FltVmV",
            desc = "DeltaCellVOLLvl2FltVmV 单体压差过大二级报警阈值",
            start_bit = 224,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "29-30",
        },
        {
            name = "CcCLVH_DeltaCellVOLLvl2FltRcvryVmV",
            desc = "DeltaCellVOLLvl2FltRcvryVmV 单体压差过大二级恢复阈值",
            start_bit = 240,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "31-32",
        },
        {
            name = "CcCLVH_DeltaCellVOLLvl3FltVmV",
            desc = "DeltaCellVOLLvl3FltVmV 单体压差过大三级报警阈值",
            start_bit = 256,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "33-34",
        },
        {
            name = "CcCLVH_DeltaCellVOLLvl3FltRcvryVmV",
            desc = "DeltaCellVOLLvl3FltRcvryVmV 单体压差过大三级恢复阈值",
            start_bit = 272,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "35-36",
        },
    },
}
