-- Auto-generated payload defs for HMI_RackCaliCtrl
-- Regenerate: python3 gen_payload_defs.py --message HMI_RackCaliCtrl

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["HMI_RackCaliCtrl"] = {
    total_bytes = 16,
    signals = {
        {
            name = "HMI_RSOXHistInfoIndicator",
            desc = "Rack History Info Calibration Indicator Rack历史累计信息指示",
            start_bit = 0,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "HMI_RSOXHistAccuCaliVal",
            desc = "Rack History Info Calibration Value Rack历史累计信息标定值",
            start_bit = 8,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "2-5",
        },
        {
            name = "HMI_AllSOCCalIndicator",
            desc = "SOC Calibration Indicator SOC标定指示",
            start_bit = 40,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "6",
        },
        {
            name = "HMI_AllSOCCalValPct",
            desc = "SOC Calibration Value (%) SOC标定值 (%)",
            start_bit = 48,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "7",
        },
        {
            name = "HMI_AllSOHCalIndicator",
            desc = "SOH Calibration Indicator SOH标定指示",
            start_bit = 56,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "8",
        },
        {
            name = "HMI_AllSOHCalValPct",
            desc = "SOH Calibration Value (%) SOH标定值 (%)",
            start_bit = 64,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "9",
        },
        {
            name = "HMI_ClrAllSoxNvMNbr",
            desc = "Clear SoX NvM Information 清除SoX NvM信息",
            start_bit = 72,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "10",
        },
        {
            name = "HMI_ForceBalCellIdx",
            desc = "Forced Balance Cell ID 强制均衡电芯ID",
            start_bit = 80,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "11-12",
        },
        {
            name = "HMI_ForceBalTiMin",
            desc = "Forced Balance Time (min) 强制均衡时间 (min)",
            start_bit = 96,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "13-14",
        },
        {
            name = "HMI_ForceBalCtrlNbr",
            desc = "Single Cell Balance Force Control Command 单电芯均衡强控开启命令",
            start_bit = 112,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "15",
        },
        {
            name = "HMI_CellBalForceCtlCmd",
            desc = "Cell Balance Force Control Cmd 电芯均衡强控命令",
            start_bit = 120,
            bit_len = 2,
            res = 1,
            off = 0,
            byte_hint = "16",
        },
    },
}
