-- Auto-generated payload defs for ParaThr_ModuleT
-- Regenerate: python3 gen_payload_defs.py --message ParaThr_ModuleT

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["ParaThr_ModuleT"] = {
    total_bytes = 56,
    signals = {
        {
            name = "CcCLTH_ChOvtempLvl1LimDegC",
            desc = "ChOverTempLvl1AssertThd 充电过温一级报警阈值",
            start_bit = 0,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "1-2",
            signed = true,
        },
        {
            name = "CcCLTH_ChOvtempLvl2LimDegC",
            desc = "ChOverTempLvl2AssertThd 充电过温二级报警阈值",
            start_bit = 16,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "3-4",
            signed = true,
        },
        {
            name = "CcCLTH_ChOvtempLvl2RcvryLimDegC",
            desc = "ChOverTempLvl2DeassertThd 充电过温二级恢复阈值",
            start_bit = 32,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "5-6",
            signed = true,
        },
        {
            name = "CcCLTH_ChOvtempLvl3LimDegC",
            desc = "ChOverTempLvl3AssertThd 充电过温三级报警阈值",
            start_bit = 48,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "7-8",
            signed = true,
        },
        {
            name = "CcCLTH_ChOvtempLvl3RcvryLimDegC",
            desc = "ChOverTempLvl3DeassertThd 充电过温三级恢复阈值",
            start_bit = 64,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "9-10",
            signed = true,
        },
        {
            name = "CcCLTH_ChUnderTLvl1LimDegC",
            desc = "ChUnderTempLvl1AssertThd 充电低温一级报警阈值",
            start_bit = 80,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "11-12",
            signed = true,
        },
        {
            name = "CcCLTH_ChUnderTLvl2LimDegC",
            desc = "ChUnderTempLvl2AssertThd 充电低温二级报警阈值",
            start_bit = 96,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "13-14",
            signed = true,
        },
        {
            name = "CcCLTH_ChUnderTLvl2RcvryLimDegC",
            desc = "ChUnderTempLvl2DeassertThd 充电低温二级恢复阈值",
            start_bit = 112,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "15-16",
            signed = true,
        },
        {
            name = "CcCLTH_ChUnderTLvl3LimDegC",
            desc = "ChUnderTempLvl3AssertThd 充电低温三级报警阈值",
            start_bit = 128,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "17-18",
            signed = true,
        },
        {
            name = "CcCLTH_ChUnderTLvl3RcvryLimDegC",
            desc = "ChUnderTempLvl3DeassertThd 充电低温三级恢复阈值",
            start_bit = 144,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "19-20",
            signed = true,
        },
        {
            name = "CcCLTH_ChOvtempLvl0LimDegC",
            desc = "ChUnderTempLvl0AssertThd 充电极限过温阈值",
            start_bit = 160,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "21-22",
            signed = true,
        },
        {
            name = "CcCLTH_DischOvtempLvl1LimDegC",
            desc = "DischOverTempLvl1AssertThd 放电过温一级报警阈值",
            start_bit = 176,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "23-24",
            signed = true,
        },
        {
            name = "CcCLTH_DischOvtempLvl2LimDegC",
            desc = "DischOverTempLvl2AssertThd 放电过温二级报警阈值",
            start_bit = 192,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "25-26",
            signed = true,
        },
        {
            name = "CcCLTH_DischOvtempLvl2RcvryLimDegC",
            desc = "DischOverTempLvl2DeassertThd 放电过温二级恢复阈值",
            start_bit = 208,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "27-28",
            signed = true,
        },
        {
            name = "CcCLTH_DischOvtempLvl3LimDegC",
            desc = "DischOverTempLvl3AssertThd 放电过温三级报警阈值",
            start_bit = 224,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "29-30",
            signed = true,
        },
        {
            name = "CcCLTH_DischOvtempLvl3RcvryLimDegC",
            desc = "DischOverTempLvl3DeassertThd 放电过温三级恢复阈值",
            start_bit = 240,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "31-32",
            signed = true,
        },
        {
            name = "CcCLTH_DischOvtempLvl0LimDegC",
            desc = "DischOverTempLvl0AssertThd 放电极限过温阈值",
            start_bit = 256,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "33-34",
            signed = true,
        },
        {
            name = "CcCLTH_CellTempRiseChangeRate",
            desc = "CellTempRiseChangeRate 温升过快极限故障阈值",
            start_bit = 272,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "35-36",
            signed = true,
        },
        {
            name = "CcCLTH_DischUnderTLvl1LimDegC",
            desc = "DischUnderTempLvl1AssertThd 放电低温一级报警阈值",
            start_bit = 288,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "37-38",
            signed = true,
        },
        {
            name = "CcCLTH_DischUnderTLvl2LimDegC",
            desc = "DischUnderTempLvl2AssertThd 放电低温二级报警阈值",
            start_bit = 304,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "39-40",
            signed = true,
        },
        {
            name = "CcCLTH_DischUnderTLvl2RcvryLimDegC",
            desc = "DischUnderTempLvl2DeassertThd 放电低温二级恢复阈值",
            start_bit = 320,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "41-42",
            signed = true,
        },
        {
            name = "CcCLTH_DischUnderTLvl3LimDegC",
            desc = "DischUnderTempLvl3AssertThd 放电低温三级报警阈值",
            start_bit = 336,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "43-44",
            signed = true,
        },
        {
            name = "CcCLTH_DischUnderTLvl3RcvryLimDegC",
            desc = "DischUnderTempLvl3DeassertThd 放电低温三级恢复阈值",
            start_bit = 352,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "45-46",
            signed = true,
        },
        {
            name = "CcCLTH_TempDiffLvl1LimDegC",
            desc = "TempDiffTooBigLvl1AssertThd 温差过大报警一级阈值",
            start_bit = 368,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "47-48",
            signed = true,
        },
        {
            name = "CcCLTH_TempDiffLvl2LimDegC",
            desc = "TempDiffTooBigLvl2AssertThd 温差过大报警二级阈值",
            start_bit = 384,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "49-50",
            signed = true,
        },
        {
            name = "CcCLTH_TempDiffLvl2RcvryLimDegC",
            desc = "TempDiffTooBigLvl2DeassertThd 温差过大报警二级恢复阈值",
            start_bit = 400,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "51-52",
            signed = true,
        },
        {
            name = "CcCLTH_TempDiffLvl3LimDegC",
            desc = "TempDiffTooBigLvl3AssertThd 温差过大报警三级阈值",
            start_bit = 416,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "53-54",
            signed = true,
        },
        {
            name = "CcCLTH_TempDiffLvl3RcvryLimDegC",
            desc = "TempDiffTooBigLvl3DeassertThd 温差过大报警三级恢复阈值",
            start_bit = 432,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "55-56",
            signed = true,
        },
    },
}
