-- Auto-generated fault bitmap profiles from SystemConfiguration xlsm FaultList
-- Regenerate: python3 gen_fault_defs.py

local FAULT_PAYLOAD_BYTES = 25
local FAULT_BIT_COUNT = 200

bms20_fault_profiles = {
    ["RBMS_Fault"] = {
        label = "RBMS_Fault",
        total_bytes = 25,
        bitmap_bytes = 25,
        bit_count = 200,
        source = "SystemConfiguration_BMS20_RBMS.xlsm",
        entries = {
            [0] = { name = "AFES_AFE_FAULT", desc = "AFE硬件故障【AFEPreFltFlg；AFEFltFlg】" },
            [1] = { name = "AFES_DAISY_CHAIN_NO_UPDATE_FAULT", desc = "菊花链通信丢失故障【DaisyChainUpdPreFltFlg；DaisyChainUpdFltFlg】" },
            [2] = { name = "AFES_CRC_FAULT", desc = "AFE采样CRC故障【AFEMsgCRCPreFltFlg；AFEMsgCRCFltFlg】" },
            [3] = { name = "AFES_CELL_VOLTAGE_SAMPLING_LINE_OFF_FAULT", desc = "电芯电压采样线掉线【CellVSamplgLineOffPreFltFlg；CellVSamplgLineOffFltFlg】" },
            [4] = { name = "AFES_DAISY_CHAIN_SINGLE_POINT_OFF_FAULT", desc = "菊花链单点断线【DaisyChainSngPointOffPreFltFlg；DaisyChainSngPointOffFltFlg】" },
            [5] = { name = "AFES_DAISY_CHAIN_MULTIPLE_POINT_OFF_FAULT", desc = "菊花链多点断线【DaisyChainMplPointOffPreFltFlg；DaisyChainMplPointOffFltFlg】" },
            [6] = { name = "CBSS_BALANCING_LOOP_CIRCUIT_FAULT", desc = "均衡回路故障【SbCBSS_BalLoopCircPreFailFlg；SbCBSS_BalLoopCircFlt】" },
            [7] = { name = "CLTS_CELL_TEMPERATURE_OUT_OF_RANGE_HIGH_FAULT", desc = "电芯温度采样短地(STG)【SbCLTS_CellTOorHiLimPreFltFlg；SbCLTS_CellTOorHiFlt】" },
            [8] = { name = "CLTS_CELL_TEMPERATURE_OUT_OF_RANGE_LOW_FAULT", desc = "电芯温度采样短电源(STB or Oc)【SbCLTS_CellTOorLoLimPreFltFlg；SbCLTS_CellTOorLoFlt】" },
            [9] = { name = "CLTS_CELL_TEMPERATURE_SAMPLING_MUX_FAULT", desc = "电芯温度采样MUX故障【SbCLTS_CellTSamplgMUXPreFltFlg；SbCLTS_CellTMUXFlt】" },
            [10] = { name = "CLVS_CELL_VOLTAGE_OUT_OF_RANGE_FAULT", desc = "电芯电压采样超范围【SaCLVS_CellVmV；SbCLVS_CellVOorFlt】" },
            [11] = { name = "HVSS_HIGH_VOLTAGE_SENSOR_FAULT", desc = "高压采样传感器故障 【BSWSHvBatVRawValVldFlg、BSWSHvLnkPosVRawValVldFlg，SbHVSS_HvSnsrPrefail；SbHVSS_HvSnsrFlt】" },
            [12] = { name = "HVSS_BATTERY_VOLTAGE_OUT_OF_RANGE_FAULT", desc = "Battery电压超范围故障 【BSWSHvBatVRawValNbr，SbHVSS_HvBatVOorPrefail；SbHVSS_HvBatVOorFlt】" },
            [13] = { name = "HVSS_LINK_POSITIVE_VOLTAGE_OUT_OF_RANGE_FAULT", desc = "LinkPos电压超范围故障【BSWSHvLnkPosVRawValNbr，SbHVSS_HvLnkPosVOorPrefail；SbHVSS_HvLnkPosVOorFlt】" },
            [14] = { name = "BTCS_CANMSG_TIMEOUT_FAULT", desc = "电流传感器通讯丢失故障【BSWSMsgAvlFlg；SbBTCS_MsgToFlt】" },
            [15] = { name = "BTCS_CANBATI_IMPLY_FAULT", desc = "电流传感器硬件故障【BSWSBatIDiagInfoFlg；SbBTCS_BatIsnsRInvalidFlt】" },
            [16] = { name = "BTCS_CANBATI_ZERODRIFT_FAULT", desc = "电流传感器零漂故障【SbBTCS_CANBatIZeroDriftFlg；SbBTCS_CANBatIZeroDriftFlt】" },
            [17] = { name = "BTCS_CANMSG_CRCRES_FAULT", desc = "电流传感器CRC故障【BSWSMsgCRCResFlg；SbBTCS_MsgCRCResFlt】" },
            [18] = { name = "ACIS_RBMS_SPD1_OPEN_FAULT", desc = "主控SPD1浪涌反馈【BSWSSPD1SrgFlg；SbACIS_Spd1OpenFlt】" },
            [19] = { name = "MCUD_RESET_FAULT", desc = "MCU故障复位原因【故障已删除】" },
            [20] = { name = "MCUD_MEMORY_INTERNAL_DATA_FAULT", desc = "MCU内部数据及存储地址错误故障【故障已删除】" },
            [21] = { name = "CLVH_MAXCELLV_OV_LEVEL1_FAULT", desc = "单体电压高一级【ScCLVH_MaxCellVmV；SbCLVH_MaxCellVoltageOverLevel1FaultFlg】" },
            [22] = { name = "CLVH_MAXCELLV_OV_LEVEL2_FAULT", desc = "单体电压高二级【ScCLVH_MaxCellVmV；SbCLVH_MaxCellVoltageOverLevel2FaultFlg】" },
            [23] = { name = "CLVH_MAXCELLV_OV_LEVEL3_FAULT", desc = "单体电压高三级【ScCLVH_MaxCellVmV；SbCLVH_MaxCellVoltageOverLevel3FaultFlg】" },
            [24] = { name = "CLVH_MINCELLV_UV_LEVEL1_FAULT", desc = "单体电压低一级【ScCLVH_MinCellVmV；SbCLVH_MinCellVoltageUnderLevel1FaultFlg】" },
            [25] = { name = "CLVH_MINCELLV_UV_LEVEL2_FAULT", desc = "单体电压低二级【ScCLVH_MinCellVmV；SbCLVH_MinCellVoltageUnderLevel2FaultFlg】" },
            [26] = { name = "CLVH_MINCELLV_UV_LEVEL3_FAULT", desc = "单体电压低三级【ScCLVH_MinCellVmV；SbCLVH_MinCellVoltageUnderLevel3FaultFlg】" },
            [27] = { name = "CLVH_DELTACELLV_OL_LEVEL1_FAULT", desc = "单体压差大一级【ScCLVH_MaxCellVmV、ScCLVH_MinCellVmV；SbCLVH_DeltaCellVoltageLargeLevel1FaultFlg】" },
            [28] = { name = "CLVH_DELTACELLV_OL_LEVEL2_FAULT", desc = "单体压差大二级【ScCLVH_MaxCellVmV、ScCLVH_MinCellVmV；SbCLVH_DeltaCellVoltageLargeLevel2FaultFlg】" },
            [29] = { name = "CLVH_DELTACELLV_OL_LEVEL3_FAULT", desc = "单体压差大三级【ScCLVH_MaxCellVmV、ScCLVH_MinCellVmV；SbCLVH_DeltaCellVoltageLargeLevel3FaultFlg】" },
            [30] = { name = "CLVH_MAXCELLV_OV_LEVEL4_FAULT", desc = "单体极限过压【ScCLVH_MaxCellVmV；SbCLVH_MaxCellVoltageOverLevel4FaultFlg】" },
            [31] = { name = "CLVH_MINCELLV_UV_LEVEL4_FAULT", desc = "单体极限欠压【ScCLVH_MinCellVmV；SbCLVH_MinCellVoltageUnderLevel4FaultFlg】" },
            [32] = { name = "CLVH_VOLTAGE_MISMATCH_FAULT", desc = "单体电压和与AFE电压不匹配【SaCLVS_CellVmV、SaCLVS_MdulVmV；SbCLVH_VoltageMismatchFlt】" },
            [33] = { name = "HVSH_HIGH_VOLTAGE_LOOP_BROKEN_FAULT", desc = "高压回路断路故障【ScCLVH_CellSumV、ScHVSS_HvBatV；SbHVSH_HvLoopBknFlt】" },
            [34] = { name = "HVSH_CELL_SUM_VOLTAGE_WITH_BATTERY_MISMTCH_FAULT", desc = "电芯电压与Battery电压不匹配【ScHVSS_HvBatV、ScCLVH_CellSumV；SbHVSH_CellSumVWithBatVMismtchFlt】" },
            [35] = { name = "ACIS_MSD_OPEN_FAULT", desc = "MSD开路(互锁)故障【BSWSMSDAuxVRawValNbr；SbACIS_MSDOpenFlt】" },
            [36] = { name = "HVSH_BATTERY_OVER_VOLTAGE_LEVEL1_FAULT", desc = "总电压过高一级【ScHVSS_HvBatV；SbHVSH_BatOVLvl1Flt】" },
            [37] = { name = "HVSH_BATTERY_OVER_VOLTAGE_LEVEL2_FAULT", desc = "总电压过高二级【ScHVSS_HvBatV；SbHVSH_BatOVLvl2Flt】" },
            [38] = { name = "HVSH_BATTERY_OVER_VOLTAGE_LEVEL3_FAULT", desc = "总电压过高三级【ScHVSS_HvBatV；SbHVSH_BatOVLvl3Flt】" },
            [39] = { name = "HVSH_BATTERY_UNDER_VOLTAGE_LEVEL1_FAULT", desc = "总电压过低一级【ScHVSS_HvBatV；SbHVSH_BatUVLvl1Flt】" },
            [40] = { name = "HVSH_BATTERY_UNDER_VOLTAGE_LEVEL2_FAULT", desc = "总电压过低二级【ScHVSS_HvBatV；SbHVSH_BatUVLvl2Flt】" },
            [41] = { name = "HVSH_BATTERY_UNDER_VOLTAGE_LEVEL3_FAULT", desc = "总电压过低三级【ScHVSS_HvBatV；SbHVSH_BatUVLvl3Flt】" },
            [42] = { name = "BTCD_DISCHARGE_OVER_CURRENT_LEVEL1_FAULT", desc = "放电电流大一级【ScBTCS_BatIA；SbBTCD_DChaOvcurLvl1】" },
            [43] = { name = "BTCD_DISCHARGE_OVER_CURRENT_LEVEL2_FAULT", desc = "放电电流大二级【ScBTCS_BatIA；SbBTCD_DChaOvcurLvl2】" },
            [44] = { name = "BTCD_DISCHARGE_OVER_CURRENT_LEVEL3_FAULT", desc = "放电电流大三级【ScBTCS_BatIA；SbBTCD_DChaOvcurLvl3】" },
            [45] = { name = "BTCD_RECHARGE_OVER_CURRENT_LEVEL1_FAULT", desc = "充电电流大一级【ScBTCS_BatIA；SbBTCD_ReChOvcurLvl1】" },
            [46] = { name = "BTCD_RECHARGE_OVER_CURRENT_LEVEL2_FAULT", desc = "充电电流大二级【ScBTCS_BatIA；SbBTCD_ReChOvcurLvl2】" },
            [47] = { name = "BTCD_RECHARGE_OVER_CURRENT_LEVEL3_FAULT", desc = "充电电流大三级【ScBTCS_BatIA；SbBTCD_ReChOvcurLvl3】" },
            [48] = { name = "CLTH_OVER_TEMPERATURE_LEVEL0_FAULT", desc = "电芯极限过温【ScCLTH_MaxCellTDegC；SbCLTH_OvtempLvl0】" },
            [49] = { name = "CLTH_DELTA_TEMPERATURE_TOO_MUCH_LEVEL1_FAULT", desc = "电芯温度差异大一级【ScCLTH_MaxCellTDegC、ScCLTH_MinCellTDegC；SbCLTH_DeltaCellTTooMuchLvl1Flt】" },
            [50] = { name = "CLTH_DELTA_TEMPERATURE_TOO_MUCH_LEVEL2_FAULT", desc = "电芯温度差异大二级【ScCLTH_MaxCellTDegC、ScCLTH_MinCellTDegC；SbCLTH_DeltaCellTTooMuchLvl2Flt】" },
            [51] = { name = "CLTH_DELTA_TEMPERATURE_TOO_MUCH_LEVEL3_FAULT", desc = "电芯温度差异大三级【ScCLTH_MaxCellTDegC、ScCLTH_MinCellTDegC；SbCLTH_DeltaCellTTooMuchLvl3Flt】" },
            [52] = { name = "CLTH_TEMPERATURE_RISE_TOO_FAST_FAULT", desc = "电芯温升过快【ScCLTH_MaxCellTDegC、ScCLTH_MinCellTDegC；SbCLTH_CellTempRiseTooFastFlt】" },
            [53] = { name = "CLTH_THERMAL_RUNAWAY_FAULT", desc = "电芯热失控故障【ScCLVH_MinCellVmV、ScCLTS_MaxCellTDegC、EbCLTH_CellTempRunAwayFlt；SbCLTH_CellTempRunAwayFlt】" },
            [54] = { name = "CLTH_PCB_BOARD_OVER_TEMPERATURE1_FAULT", desc = "从板均衡温度高一级【SbCLTH_PCBBdTVldFlg、ScCLTH_MaxPCBTDegC；SbCLTH_PCBOvrTFlt】" },
            [55] = { name = "CLTH_PCB_BOARD_OVER_TEMPERATURE2_FAULT", desc = "从板均衡温度高二级【SbCLTH_PCBBdTVldFlg、ScCLTH_MaxPCBTDegC；SbCLTH_PCBOvrTLvl2Flt】" },
            [56] = { name = "AFES_AFE_OVER_TEMPERATURE_FAULT", desc = "AFE芯片过温报警【ChipTOverPreFltFlg；ChipTOverFltFlg】" },
            [57] = { name = "CLTH_HV_BOX_AMBIENT_OVER_TEMP_LEVEL1_FAULT", desc = "高压盒过温一级【ScCLTH_CtlBoxTMaxDegC；SbCLTH_AmbientOvTLvl1Flt】" },
            [58] = { name = "CLTH_HV_BOX_AMBIENT_OVER_TEMP_LEVEL2_FAULT", desc = "高压盒过温二级【ScCLTH_CtlBoxTMaxDegC；SbCLTH_AmbientOvTLvl2Flt】" },
            [59] = { name = "CLTH_HV_BOX_AMBIENT_OVER_TEMP_LEVEL3_FAULT", desc = "高压盒过温三级【ScCLTH_CtlBoxTMaxDegC；SbCLTH_AmbientOvTLvl3Flt】" },
            [60] = { name = "LVPH_RELAY_POWER_SUPPLY_OVER_VOLTAGE_FAULT", desc = "继电器供电电压过高故障【ScLVPS_RlyPowSplyValV、SbLVPS_RlyPowSplyVldFlg、SbMCUD_MCUChipADCPrefailFlg；SbLVPH_RlyPowSplyOVFlt】" },
            [61] = { name = "LVPH_RELAY_POWER_SUPPLY_UNDER_VOLTAGE_FAULT", desc = "继电器供电电压过低故障【ScLVPS_RlyPowSplyValV、SbLVPS_RlyPowSplyVldFlg、SbMCUD_MCUChipADCPrefailFlg；SbLVPH_RlyPowSplyUVFlt】" },
            [62] = { name = "LVPH_CURRENT_SENSOR_POWER_SUPPLY_OVER_VOLTAGE_FAULT", desc = "电流传感器供电电压过高故障【ScLVPS_CurrSnsrPowSplyValV、SbLVPS_CurrSnsrPowSplyVldFlg、SbMCUD_MCUChipADCPrefailFlg；SbLVPH_CurrSnsrPowSplyOVFlt】" },
            [63] = { name = "LVPH_CURRENT_SENSOR_POWER_SUPPLY_UNDER_VOLTAGE_FAULT", desc = "电流传感器供电电压过低故障【ScLVPS_CurrSnsrPowSplyValV、SbLVPS_CurrSnsrPowSplyVldFlg、SbMCUD_MCUChipADCPrefailFlg；SbLVPH_CurrSnsrPowSplyUVFlt】" },
            [64] = { name = "LVPH_24V_INTERNAL_POWER_SUPPLY_OVER_VOLTAGE_FAULT", desc = "RBMS供电电压过高故障【ScLVPS_24VIntPowSplyValV、SbLVPS_24VIntPowSplyVldFlg、SbMCUD_MCUChipADCPrefailFlg；SbLVPH_24VIntPowSplyOVFlt】" },
            [65] = { name = "LVPH_24V_INTERNAL_POWER_SUPPLY_UNDER_VOLTAGE_FAULT", desc = "RBMS供电电压过低故障【ScLVPS_24VIntPowSplyValV、SbMCUD_MCUChipADCPrefailFlg、SbLVPS_24VIntPowSplyVldFlg；SbLVPH_24VIntPowSplyUVFlt】" },
            [66] = { name = "LVPH_HIGH_VOLTAGE_SENSOR_POWER_SUPPLY_UNDER_VOLTAGE_FAULT", desc = "高压采样芯片供电电压过低故障【ScLVPS_HvSnsrPowSplyValV；SbLVPH_HvSnsrPowSplyUVFlt】" },
            [67] = { name = "ISOH_ISOLATION_LOW_LEVEL1_FAULT", desc = "高压绝缘低一级【ScISOH_IslnMeastValkOhms；SbISOH_IsLow1Flt】" },
            [68] = { name = "ISOH_ISOLATION_LOW_LEVEL2_FAULT", desc = "高压绝缘低二级【ScISOH_IslnMeastValkOhms；SbISOH_IsLow2FltFlg】" },
            [69] = { name = "ISOH_ISOLATION_LOW_LEVEL3_FAULT", desc = "高压绝缘低三级【ScISOH_IslnMeastValkOhms；SbISOH_IsLow3Flt】" },
            [70] = { name = "ISOH_ISOLATION_VALUE_INVALID_FAULT", desc = "绝缘无效故障【ScISOH_IslnFinalPosV、ScISOH_IslnFinalNegV；SbISOH_IslnVOorFlt】" },
            [71] = { name = "CBCC_SELF_DISCHARGE_DIFFERENCE_OVER_HIGH1_FAULT", desc = "电芯自放电差异过大一级【ScCBCC_MaxCellSelfDischRtoPct；SbCBCC_CellSelfDischOverHighLvl1Flt】" },
            [72] = { name = "CBCC_SELF_DISCHARGE_DIFFERENCE_OVER_HIGH2_FAULT", desc = "电芯自放电差异过大二级【ScCBCC_MaxCellSelfDischRtoPct；SbCBCC_CellSelfDischOverHighLvl2Flt】" },
            [73] = { name = "CBCC_SELF_DISCHARGE_DIFFERENCE_OVER_HIGH3_FAULT", desc = "电芯自放电差异过大三级【ScCBCC_MaxCellSelfDischRtoPct；SbCBCC_CellSelfDischOverHighLvl3Flt】" },
            [74] = { name = "SOCA_RACK_OVER_CHARGE_FAULT", desc = "Rack过充【；SbSOCA_OverChgFltFlg】" },
            [75] = { name = "CTSC_PRECHARGE_OVER_TIME_FAULT", desc = "预充超时故障【SbCTSC_PrechOverTiPreFailFlg；SbCTSC_PrechOverTiFlt】" },
            [76] = { name = "CTSC_PRECHARGE_OVER_CURRENT_FAULT", desc = "预充过流故障【SbCTSC_PrechOverCurrPreFailFlg；SbCTSC_PrechOverCurrFlt】" },
            [77] = { name = "CTSC_RBMS_EPO_OPEN_FAULT", desc = "主控EPO开 【故障已删除】" },
            [78] = { name = "ACIS_RBMS_QS_OPEN_FAULT", desc = "隔离开关开【BSWSQSAuxVRawValNbr；SbACIS_QSOpenFlt】" },
            [79] = { name = "EMCR_RANK_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "Bank通信丢失故障【BBMS_Heartbeat；SbEMCR_CommLostFlg】" },
            [80] = { name = "EMCR_CRC_FAULT", desc = "Bank通信CRC异常故障【BSWSExtMsgCRCResFlg；SbEMCR_CRCResFlg】" },
            [81] = { name = "ISOH_INVALID_ISOLATION_POSV_FAULT", desc = "绝缘正对地电压故障【BSWSIslnPosVRawValVldFlg；SbISOH_InvlIsoPosVFlt】" },
            [82] = { name = "ISOH_INVALID_ISOLATION_NEGV_FAULT", desc = "绝缘负对地电压故障【BSWSIslnNegVRawValVldFlg；SbISOH_InvalIsoNegVFlt】" },
            [83] = { name = "CLTH_CELL_POLE_DELTA_TEMPERATURE_OVER_LEVEL1_FAULT", desc = "电芯单体温度与电芯极柱温度偏差过大一级故障【ScCLTH_MaxCellTDegC、ScCLTH_MinCellTDegC、ScCLTH_MaxPoleTDegC、ScCLTH_MinPoleTDegC；SbCLTH_CellPoleOvTempDiffLvl1】" },
            [84] = { name = "SOCA_SOC_TOO_LOW_LEVEL1_FAULT", desc = "SOC低一级【ScSOCA_DispSysSOCPct；SbSOCA_SOCTooLowLvl1FltFlg】" },
            [85] = { name = "SOCA_SOC_TOO_LOW_LEVEL2_FAULT", desc = "SOC低二级【ScSOCA_DispSysSOCPct；SbSOCA_SOCTooLowLvl2FltFlg】" },
            [86] = { name = "SOCA_SOC_DIFFER_VALUE_OVER_HIGH_FAULT", desc = "SOC差异过大【ScSOCA_SysMaxSOCPct，ScSOCA_SysMinSOCPct；SbSOCA_SOCDifferValueOverHighFltFlg】" },
            [87] = { name = "SOHA_SOH_TOO_LOW_LEVEL1_FAULT", desc = "SOH低一级【ScSOHA_RealSysSOHCPct；SbSOHA_SOHTooLowLvl1Flt】" },
            [88] = { name = "SOHA_SOH_TOO_LOW_LEVEL2_FAULT", desc = "SOH低二级【ScSOHA_RealSysSOHCPct；SbSOHA_SOHTooLowLvl2Flt】" },
            [89] = { name = "SOHA_SOH_TOO_LOW_LEVEL3_FAULT", desc = "SOH低三级【ScSOHA_RealSysSOHCPct；SbSOHA_SOHTooLowLvl3Flt】" },
            [90] = { name = "CTSC_COMBINE_SWITCH_VOLT_LOW_FAULT", desc = "融合开关欠压故障【ScLVPS_RlyPowSplyValV；SbCTSC_CombineSwVoltLowFlt】" },
            [91] = { name = "SOCA_SOC_TOO_LOW_LEVEL3_FAULT", desc = "SOC低三级【ScSOCA_DispSysSOCPct；SbSOCA_SOCTooLowLvl3FltFlg】" },
            [92] = { name = "SOCA_SOC_TOO_HIGH_LEVEL1_FAULT", desc = "SOC高一级【ScSOCA_DispSysSOCPct；SbSOCA_SOCTooHighLvl1FltFlg】" },
            [93] = { name = "SOCA_SOC_TOO_HIGH_LEVEL2_FAULT", desc = "SOC高二级【ScSOCA_DispSysSOCPct；SbSOCA_SOCTooHighLvl2FltFlg】" },
            [94] = { name = "SOCA_SOC_TOO_HIGH_LEVEL3_FAULT", desc = "SOC高三级【ScSOCA_DispSysSOCPct；SbSOCA_SOCTooHighLvl3FltFlg】" },
            [95] = { name = "CLTH_POLE_OVER_TEMPERATURE_LEVEL1_FAULT", desc = "极柱温度过温一级告警【ScCLTH_MaxPoleTDegC；SbCLTH_PoleOverTempLvl1FltFlg】" },
            [96] = { name = "CLTH_POLE_OVER_TEMPERATURE_LEVEL2_FAULT", desc = "极柱温度过温二级告警【ScCLTH_MaxPoleTDegC；SbCLTH_PoleOverTempLvl2FltFlg】" },
            [97] = { name = "CLTH_POLE_OVER_TEMPERATURE_LEVEL3_FAULT", desc = "极柱温度过温三级告警【ScCLTH_MaxPoleTDegC；SbCLTH_PoleOverTempLvl3FltFlg】" },
            [98] = { name = "CLTH_CHG_OVER_TEMPERATURE_LEVEL1_FAULT", desc = "电芯充电温度过高一级报警【ScCLTH_MaxCellTDegC；SbCLTH_ChgOvtempLvl1】" },
            [99] = { name = "CLTH_CHG_OVER_TEMPERATURE_LEVEL2_FAULT", desc = "电芯充电温度过高二级报警【ScCLTH_MaxCellTDegC；SbCLTH_ChgOvtempLvl2】" },
            [100] = { name = "CLTH_CHG_OVER_TEMPERATURE_LEVEL3_FAULT", desc = "电芯充电温度过高三级报警【ScCLTH_MaxCellTDegC；SbCLTH_ChgOvtempLvl3】" },
            [101] = { name = "CLTH_DSG_OVER_TEMPERATURE_LEVEL1_FAULT", desc = "电芯放电温度过高一级报警【ScCLTH_MaxCellTDegC；SbCLTH_DsgOvtempLvl1】" },
            [102] = { name = "CLTH_DSG_OVER_TEMPERATURE_LEVEL2_FAULT", desc = "电芯放电温度过高二级报警【ScCLTH_MaxCellTDegC；SbCLTH_DsgOvtempLvl2】" },
            [103] = { name = "CLTH_DSG_OVER_TEMPERATURE_LEVEL3_FAULT", desc = "电芯放电温度过高三级报警【ScCLTH_MaxCellTDegC；SbCLTH_DsgOvtempLvl3】" },
            [104] = { name = "CLTH_CHG_UNDER_TEMPERATURE_LEVEL1_FAULT", desc = "电芯充电温度过低一级报警【ScCLTH_MinCellTDegC；SbCLTH_ChgUndertempLvl1】" },
            [105] = { name = "CLTH_CHG_UNDER_TEMPERATURE_LEVEL2_FAULT", desc = "电芯充电温度过低二级报警【ScCLTH_MinCellTDegC；SbCLTH_ChgUndertempLvl2】" },
            [106] = { name = "CLTH_CHG_UNDER_TEMPERATURE_LEVEL3_FAULT", desc = "电芯充电温度过低三级报警【ScCLTH_MinCellTDegC；SbCLTH_ChgUndertempLvl3】" },
            [107] = { name = "CLTH_DSG_UNDER_TEMPERATURE_LEVEL1_FAULT", desc = "电芯放电温度过低一级报警【ScCLTH_MinCellTDegC；SbCLTH_DsgUndertempLvl1】" },
            [108] = { name = "CLTH_DSG_UNDER_TEMPERATURE_LEVEL2_FAULT", desc = "电芯放电温度过低二级报警【ScCLTH_MinCellTDegC；SbCLTH_DsgUndertempLvl2】" },
            [109] = { name = "CLTH_DSG_UNDER_TEMPERATURE_LEVEL3_FAULT", desc = "电芯放电温度过低三级报警【ScCLTH_MinCellTDegC；SbCLTH_DsgUndertempLvl3】" },
            [110] = { name = "CLVH_MODULE_OVER_VOLTAGE_LEVEL1_FAULT", desc = "模组电压高一级【ScCLVH_MaxCellVmV；SbCLVH_ModuleOverVoltageLevel1FaultFlg】" },
            [111] = { name = "CLVH_MODULE_OVER_VOLTAGE_LEVEL2_FAULT", desc = "模组电压高二级【ScCLVH_MaxCellVmV；SbCLVH_ModuleOverVoltageLevel2FaultFlg】" },
            [112] = { name = "CLVH_MODULE_OVER_VOLTAGE_LEVEL3_FAULT", desc = "模组电压高三级【ScCLVH_MaxCellVmV；SbCLVH_ModuleOverVoltageLevel3FaultFlg】" },
            [113] = { name = "CLVH_MODULE_UNDER_VOLTAGE_LEVEL1_FAULT", desc = "模组电压低一级【ScCLVH_MinCellVmV；SbCLVH_ModuleUnderVoltageLevel1FaultFlg】" },
            [114] = { name = "CLVH_MODULE_UNDER_VOLTAGE_LEVEL2_FAULT", desc = "模组电压低二级【ScCLVH_MinCellVmV；SbCLVH_ModuleUnderVoltageLevel2FaultFlg】" },
            [115] = { name = "CLVH_MODULE_UNDER_VOLTAGE_LEVEL3_FAULT", desc = "模组电压低三级【ScCLVH_MinCellVmV；SbCLVH_ModuleUnderVoltageLevel3FaultFlg】" },
            [116] = { name = "CTSC_MAIN_NEGATIVE_RELAY_STUCK_CLOSE_FAULT", desc = "主负继电器粘连故障【SbCTSC_MainNegRelayStuckClosePrefail；SbCTSC_MainNegRelayStuckCloseFlt】" },
            [117] = { name = "CTSC_MAIN_NEGATIVE_RELAY_STUCK_OPEN_FAULT", desc = "主负继电器开路故障【SbCTSC_MainNegRelayStuckOpenPrefail；SbCTSC_MainNegRelayStuckOpenFlt】" },
            [118] = { name = "CTSC_MAIN_POSITIVE_RELAY_STUCK_CLOSE_FAULT", desc = "主正继电器粘连故障【SbCTSC_MainPosRelayStuckClosePrefail；SbCTSC_MainPosRelayStuckCloseFlt】" },
            [119] = { name = "CTSC_MAIN_POSITIVE_RELAY_STUCK_OPEN_FAULT", desc = "主正继电器开路故障【SbCTSC_MainPosRelayStuckOpenPrefail；SbCTSC_MainPosRelayStuckOpenFlt】" },
            [120] = { name = "CTSC_MAINPOS_AUX_CONTACT_ST_FAULT", desc = "主正继电器辅助触点电路故障【故障已删除】" },
            [121] = { name = "CTSC_MAINNEG_AUX_CONTACT_ST_FAULT", desc = "主负继电器辅助触点电路故障【故障已删除】" },
            [122] = { name = "ACIS_RBMS_DOOR_OPEN_FAULT", desc = "门禁故障【BSWSDoorOpenFlg;SbACIS_DoorOpenFlg】" },
            [123] = { name = "CLVS_AFE_VOLTAGE_OUT_OF_RANGE_FAULT", desc = "AFE电压采样超范围【SaCLVS_MdulVmV；SbCLVS_MdulVOorFlt】" },
            [124] = { name = "BTCD_RECHARGE_OVER_CURRENT_LEVEL0_FAULT", desc = "充电极限过流报警【ScBTCS_BatIA；SbBTCD_ReChOvcurLvl0】" },
            [125] = { name = "BTCD_DISCHARGE_OVER_CURRENT_LEVEL0_FAULT", desc = "放电极限过流报警【ScBTCS_BatIA；SbBTCD_DChaOvcurLvl0】" },
            [126] = { name = "LVPS_RELAY_POWER_SUPPLY_OVERORUNDER_VOLTAGE_FAULT", desc = "继电器供电电压超范围故障【BSWSRlyPowSplyRawValVCnt，SbLVPS_RlyPwrSplyOvUnFltPreFlg；SbLVPS_RlyPwrSplyOvUnFlt】" },
            [127] = { name = "LVPS_CURRENT_SENSOR_POWER_SUPPLY_OVERORUNDER_VOLTAGE_FAULT", desc = "电流传感器供电电压超范围故障【BSWSCurrSnsrPowSplyRawValVCnt，SbLVPS_24VIntPowSplyOvUnFltPreFlg；SbLVPS_CurrSnsrPowSplyOvUnFlt】" },
            [128] = { name = "LVPS_24V_INTERNAL_POWER_SUPPLY_OVERORUNDER_VOLTAGE_FAULT", desc = "RBMS供电电压超范围故障【BSWS24VIntPowSplyRawValVCnt，SbLVPS_CurrSnsrPowSplyOvUnFltPreFlg；SbLVPS_24VIntPowSplyOvUnFlt】" },
            [129] = { name = "CLTH_UNDER_TEMPERATURE_LEVEL0_FAULT", desc = "电芯极限欠温【ScCLTH_MinCellTDegC；SbCLTH_UndertempLvl0】" },
            [130] = { name = "CLTS_CELL_TEMPERATURE_REDUNDANT_DETECT_FAULT", desc = "电芯温度冗余检测故障【SbCLTS_CellTRedunChkPreFltFlg；SbCLTS_CellTRedunChkFlt】" },
            [131] = { name = "EMCR_EMERGENCY_SHUTDOWN_SIGNAL_TIMEOUT_FAULT", desc = "紧急关断信号CAN通信超时故障【BSWSEmgShdnSigTimeoutFlg、SbEMCR_EmgShdnSigTimeoutFltFlg】" },
            [132] = { name = "EMCR_EMERGENCY_SHUTDOWN_SIGNAL_CRC_FAULT", desc = "紧急关断信号CAN通信CRC故障【BSWSEmgShdnSigCRCErrFlg、SbEMCR_EmgShdnSigCRCErrFltFlg】" },
            [133] = { name = "EMCR_EMERGENCY_SHUTDOWN_SIGNAL_COUNTER_FAULT", desc = "紧急关断信号CAN通信Counter故障【BSWSEmgShdnSigCounterErrFlg、SbEMCR_EmgShdnSigCounterErrFltFlg】" },
            [134] = { name = "MCUD_INIT_FAULT", desc = "MCU初始化故障【BSWSMCUInitFltNbr；SbMCUD_MCUInitFlt】" },
            [135] = { name = "MCUD_CHIP_GPIO_FAULT", desc = "MCU芯片GPIO模块故障【BSWSMCUChipFltNbr；SbMCUD_MCUChipGPIOFlt】" },
            [136] = { name = "MCUD_CHIP_SPI_FAULT", desc = "MCU芯片SPI模块故障【BSWSMCUChipFltNbr；SbMCUD_MCUChipSPIFlt】" },
            [137] = { name = "MCUD_CHIP_CAN_FAULT", desc = "MCU芯片CAN模块故障【BSWSMCUChipFltNbr；SbMCUD_MCUChipCANFlt】" },
            [138] = { name = "MCUD_CHIP_ADC_FAULT", desc = "MCU芯片ADC模块故障【BSWSMCUChipFltNbr；SbMCUD_MCUChipADCFlt】" },
            [139] = { name = "CTSC_MAIN_POSITIVE_RELAY_DRIVER_CIRCUIT_FAULT", desc = "主正继电器驱动电路故障【SbCTSC_MainPosRlyDrvCrctFltPreFailFlg；SbCTSC_MainPosRlyDriverCircuitFlt】" },
            [140] = { name = "CTSC_MAIN_NEGATIVE_RELAY_DRIVER_CIRCUIT_FAULT", desc = "主负继电器驱动电路故障【SbCTSC_MainNegRlyDrvCrctFltPreFailFlg；SbCTSC_MainNegRlyDriverCircuitFlt】" },
            [141] = { name = "CTSC_RELAY_DRIVER_SAMPLING_SELECT_CHANNEL_FAULT", desc = "继电器驱动回采选通故障【SbCTSC_RlyDrvSmplSlctChnnlPreFailFlg；SbCTSC_RlyDrvSmplSlctChnnlFlt】" },
            [142] = { name = "ACIS_FIRE_EXTINGUISHER_ALERT_FAULT", desc = "消防一级故障【BSWSFireExtAlertFlg；SbACIS_FireExtAlertFlt】" },
            [143] = { name = "SGPC_RTC_TIME_INVALID_FAULT", desc = "RTC时间无效故障【RTCTimeInvalidPreFltFlg；RTCTimeInvalidFltFlg】" },
            [144] = { name = "ACIS_HV_FUSE_FAULT", desc = "高压箱熔断器故障【BSWSHighVFuseFlg；SbACIS_HighVFuseFlt】" },
            [145] = { name = "CLTH_PACKPOSNEGCONN_OVER_TEMPERATURE_LEVEL1_FAULT", desc = "Pack正负极连接件温度过温一级告警【ScCLTH_PackPosNegConnTDegC；SbCLTH_PackPosNegConnOverTempLvl1FltFlg】" },
            [146] = { name = "CLTH_PACKPOSNEGCONN_OVER_TEMPERATURE_LEVEL2_FAULT", desc = "Pack正负极连接件温度过温二级告警【ScCLTH_PackPosNegConnTDegC；SbCLTH_PackPosNegConnOverTempLvl2FltFlg】" },
            [147] = { name = "CLTH_PACKPOSNEGCONN_OVER_TEMPERATURE_LEVEL3_FAULT", desc = "Pack正负极连接件温度过温三级告警【ScCLTH_PackPosNegConnTDegC；SbCLTH_PackPosNegConnOverTempLvl3FltFlg】" },
            [148] = { name = "CLTS_PCB_BOARD_TEMP_SENSOR_SHORT_TO_GROUND_FAULT", desc = "从板均衡温度采样短地(STG)【BSWSTRawValNbr；SbCLTS_PCBBdTSTGFlt】" },
            [149] = { name = "CLTS_PCB_BOARD_TEMP_SENSOR_SHORT_TO_BATTERY_FAULT", desc = "从板均衡温度采样短电源(STB or Oc)【BSWSTRawValNbr；SbCLTS_PCBBdTSTBFlt】" },
            [150] = { name = "CLVH_DELTAMODULEV_OL_LEVEL1_FAULT", desc = "模组压差大一级【ScCLVH_MaxModuleVmV、ScCLVH_MinModuleVmV；SbCLVH_DeltaModuleVoltageLargeLevel1FaultFlg】" },
            [151] = { name = "CLVH_DELTAMODULEV_OL_LEVEL2_FAULT", desc = "模组压差大二级【ScCLVH_MaxModuleVmV、ScCLVH_MinModuleVmV；SbCLVH_DeltaModuleVoltageLargeLevel2FaultFlg】" },
            [152] = { name = "CLVH_DELTAMODULEV_OL_LEVEL3_FAULT", desc = "模组压差大三级【ScCLVH_MaxModuleVmV、ScCLVH_MinModuleVmV；SbCLVH_DeltaModuleVoltageLargeLevel3FaultFlg】" },
            [153] = { name = "AFES_DAISY_CHAIN_COUNTER_ERROR_FAULT", desc = "菊花链通信Counter故障【DaisyChainCounterPreFltFlg；DaisyChainCounterFltFlg】" },
            [154] = { name = "AFES_CELL_VOLTAGE_REDUNDABCY_DETECT_FAULT", desc = "电芯电压冗余检测故障【CellADCSampleErrorPreFltFlg；CellADCSampleErrorFltFlg】" },
            [155] = { name = "AFES_NTC_POWER_SUPPLY_FAULT", desc = "NTC供电故障【NTCPowerSupplyPreFltFlg；NTCPowerSupplyFltFlg】" },
            [156] = { name = "HVSH_MAIN_POSITIVE_BUS_BROKEN_FAULT", desc = "主正连接母线断路故障【SbHVSH_MainPosBusBknPreFlt；SbHVSH_MainPosBusBknFlt】" },
            [157] = { name = "ACIS_COOL_FAN_FAULT", desc = "散热风扇故障【BSWSCoolingFanFlg；SbACIS_CoolingFanFlt】" },
            [158] = { name = "ACIS_SMOKE_FEEDBACK_FAULT", desc = "烟感故障【BSWSSmokeFdbkFlg；SbACIS_SmokeFdbkFlt】" },
            [159] = { name = "ACIS_TEMP_FEEDBACK_FAULT", desc = "温感故障【BSWSTempFdbkFlg；SbACIS_TempFdbkFlt】" },
            [160] = { name = "ACIS_ESTOP_FAULT", desc = "急停故障【BSWSEStopFlg】" },
            [161] = { name = "ACIS_WATER_FLOOD_FAULT", desc = "水浸告警故障【BSWSWtrFldFlg】" },
            [162] = { name = "ACIS_QF1_BREAKER_FAULT", desc = "QF1断路器故障【BSWSQF1BrkFlg】" },
            [163] = { name = "ACIS_AEROSOL_FAULT", desc = "气溶胶故障1【BSWSAerosolFlg；SbACIS_AerosolFlt】" },
            [164] = { name = "ACIS_AEROSOL2_FAULT", desc = "气溶胶故障2【BSWSAerosol2Flg；SbACIS_Aerosol2Flt】" },
            [165] = { name = "EMCR_DEHUMIDIFIER_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "除湿机通讯节点丢失故障【BSWSDehumidifierMsgAvlFlg、SbEMCR_DehumidifierComLostFltFlg】" },
            [166] = { name = "EMCR_IOModule_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "IO模块通讯节点丢失故障【BSWSIOModuleMsgAvlFlg、SbEMCR_IOModuleComLostFltFlg】" },
            [167] = { name = "EMCR_PCS_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "PCS通信丢失故障【BSWSPCSHeartbeat】" },
            [168] = { name = "BTCD_SHORT_CIRCUIT_FAULT", desc = "总线短路故障【ScBTCS_BatIA；SbBTCD_ShortCircuitFlt】" },
            [169] = { name = "BTCS_HALLSENS_OVERRANGE_FAULT", desc = "电流传感器超量程故障【BSWSOverCurIndFlg；SbBTCS_HallSensOverRangeFlt】" },
            [170] = { name = "LVPH_HIGH_VOLTAGE_SENSOR_POWER_SUPPLY_OVER_VOLTAGE_FAULT", desc = "高压采样芯片供电电压过高故障【ScLVPS_HvSnsrPowSplyValV；SbLVPH_HvSnsrPowSplyOVFlt】" },
            [171] = { name = "CTSC_PRECHRG_RELAY_STUCK_CLOSE_FAULT", desc = "预充继电器粘连故障【SbCTSC_PreChrgRlyStuckClosePreFailFlg；SbCTSC_PreChrgRlyStuckCloseFlt】" },
        },
    },
    ["BBMS_Fault_M"] = {
        label = "BBMS_Fault (M核)",
        total_bytes = 26,
        bitmap_bytes = 25,
        bit_count = 200,
        source = "SystemConfiguration_BMS20M_BBMS.xlsm",
        tail_fields = {
            { name = "BBMSNo", start_bit = 200, bit_len = 4, desc = "Bank Number 堆编号" },
        },
        entries = {
            [0] = { name = "EMCR_ALLRACK_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "所有RBMS通讯丢失【SbEMCR_AllRackCommLostPreFltFlg；SbEMCR_AllRackCommLostFltFlg】" },
            [1] = { name = "EMCR_ONERACK_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "至少一个RBMS通讯丢失【SbEMCR_OneRackCommLostPreFltFlg；SbEMCR_OneRackCommLostFltFlg】" },
            [2] = { name = "BKPC_DELTA_BRANCH_OVERTEMP_FAULT", desc = "所有簇温差过大故障【SbBKPC_DeltaTempOverPreFltFlg；SbBKPC_DeltaTempOverFlt】" },
            [3] = { name = "BKPC_DELTA_BRANCH_OVERCURRENT_LEVEL1_FAULT", desc = "电池簇间环流越限1级【SbBKPC_DeltaCurrOverLv1PreFltFlg；SbBKPC_DeltaCurrOverLv1Flt】" },
            [4] = { name = "BKPC_DELTA_BRANCH_OVERCURRENT_LEVEL2_FAULT", desc = "电池簇间环流越限2级【SbBKPC_DeltaCurrOverLv2PreFltFlg；SbBKPC_DeltaCurrOverLv2Flt】" },
            [5] = { name = "BKPC_DELTA_BRANCH_OVERCURRENT_LEVEL3_FAULT", desc = "电池簇间环流越限3级【SbBKPC_DeltaCurrOverLv3PreFltFlg；SbBKPC_DeltaCurrOverLv3Flt】" },
            [6] = { name = "EMCR_PCS_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "PCS通信丢失故障【BSWSPCSHeartbeat；SbEMCR_PCSCommLostFltFlg】" },
            [7] = { name = "BCFR_EXCESSIVE_VOLTAGE_DIFF_FAULT", desc = "簇间压差过大故障【SaEMCR_RackV，SbBCFR_ExcVoltDiffPreFltFlg；SbBCFR_ExcessiveVoltDiffFlt】" },
            [8] = { name = "ACIS_IDLEARN_FAILED_FAULT", desc = "IDLearm编码失败【BSWSIDLearnSt；SbACIS_IDLearnFailedFlt】" },
            [9] = { name = "THMC_TMS_REQUEST_DIFF_FAULT", desc = "水冷机组工作模式不匹配故障【ScTMCR_TMSWorkMode，ScTHMC_RqrdTMSWrStState；SbTHMC_TMSWorkStDiffFlg】" },
            [10] = { name = "THMC_TMS_LEVEL1_FAULT", desc = "水冷机一级故障【ScTMCR_TMSFltLevelState，SbTMCR_TMSMsgAvlFlg；SbTHMC_TMSLvl1Flt】" },
            [11] = { name = "THMC_TMS_LEVEL2_FAULT", desc = "水冷机二级故障【ScTMCR_TMSFltLevelState，SbTMCR_TMSMsgAvlFlg；SbTHMC_TMSLvl2Flt】" },
            [12] = { name = "TMCR_TMS_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "TMS通讯丢失【BSWSTMSMsgAvlFlg】" },
            [13] = { name = "LVPS_24V_INTERNAL_POWER_SUPPLY_OVERORUNDER_VOLTAGE_FAULT", desc = "24V电压超范围故障【【BMS2.0三级板硬件无低压采样】；ScLVPS_24VIntPowSplyValV，SbLVPS_24VIntPowSplyVldFlg，SbLVPS_24VIntPowSplyOVPrefail；SbLVPS_24VIntPowSplyOVFlt】" },
            [14] = { name = "LVPS_12V_INTERNAL_POWER_SUPPLY_OVERORUNDER_VOLTAGE_FAULT", desc = "12V电压超范围故障【【BMS2.0三级板硬件无低压采样】；ScLVPS_12VIntPowSplyValV，SbLVPS_12VIntPowSplyVldFlg，SbLVPS_12VIntPowSplyOVPrefail；SbLVPS_12VIntPowSplyOVFlt】" },
            [15] = { name = "BSOX_OVERPOWER_FAULT", desc = "过功率故障【SbBSOX_OverPowPreFlt，SbBSOX_OverPowFlt】" },
            [16] = { name = "BSOX_SOC_DIFF_FAULT", desc = "Rack间SOC差距过大故障【SbBSOX_SOCDiffPreFlt，SbBSOX_SOCDiffFlt】" },
            [17] = { name = "ACIS_DOOR_OPEN_FAULT", desc = "门禁故障【BSWSDoorOpenFlg；SbACIS_DoorOpenFlt】" },
            [18] = { name = "ACIS_QF1_BREAKER_FAULT", desc = "QF1断路器故障【BSWSQF1BrkFlg；SbACIS_QF1BrkFlt】" },
            [19] = { name = "ACIS_SPD2_SURGE_FAULT", desc = "SPD2浪涌故障【BSWSSPD2SrgFlg；SbACIS_SPD2SrgFlt】" },
            [20] = { name = "ACIS_WATER_FLOOD_FAULT", desc = "水浸告警故障【BSWSWtrFldFlg；SbACIS_WtrFldFlt】" },
            [21] = { name = "ACIS_CONBUSTILE_GAS_FAULT", desc = "可燃气体告警故障【BSWSCmbstlGasFlg；SbACIS_CmbstlGasFlt】" },
            [22] = { name = "ACIS_EXPLOSIONPROOF_FAN_FAULT", desc = "防爆风机告警故障【BSWSExpprfFanFlg；SbACIS_ExpprfFanFlt】" },
            [23] = { name = "ACIS_ESTOP_FAULT", desc = "急停故障【BSWSEStopFlg;SbACIS_EStopFlt】" },
            [24] = { name = "ACIS_FIRE_EXTINGUISHER_ALERT_FAULT", desc = "消防严重告警【BSWSFireExtAlertFlg；SbACIS_FireExtAlertFlt】" },
            [25] = { name = "ACIS_FIRE_EXTINGUISHER_ALARM_FAULT", desc = "消防中度告警【BSWSFireExtAlarmFlg；SbACIS_FireExtAlarmFlt】" },
            [26] = { name = "ACIS_FIRE_EXTINGUISHER_WARN_FAULT", desc = "消防故障【BSWSFireExtWarnFlg；SbACIS_FireExtWarnFlt】" },
            [27] = { name = "EMCR_UPS_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "UPS通讯节点丢失故障【BSWSUPSHeartbeat、SbEMCR_UPSCommLostFltFlg】" },
            [28] = { name = "EMCR_ENERGYMETER_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "电表通讯节点丢失故障【BSWSEnymetrHeartbeat、SbEMCR_EnergymeterCommLostFltFlg】" },
            [29] = { name = "ACIS_PCS_EPO_FAULT", desc = "PCS急停故障【BSWSPCSEPOFlg；SbACIS_PCSEPOFlt】" },
            [30] = { name = "ACIS_CONTAINER_EPO_FAULT", desc = "集装箱急停故障【BSWSDistriCabEPOFlg；SbACIS_DistrCabEPOFlt】" },
            [31] = { name = "ACIS_DISTRIBUTION_CAB_EPO_FAULT", desc = "配电柜急停故障【BSWSContainerEPOFlg；SbACIS_ContainerEPOFlt】" },
            [32] = { name = "EMCR_EMS_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "EMS通讯节点丢失故障【BSWEMSMsgAvlFlg、SbEMCR_EMSCommLostFltFlg】" },
            [33] = { name = "EMCR_BATTERYCABIN_DEHUMIDIFIER_TO_BMS_COMM_LOST_FAULT", desc = "电池舱除湿机通讯节点丢失故障【BSWDehumidifierMsgAvlFlg、SbEMCR_DehumidifierComLostFltFlg】" },
            [34] = { name = "EMCR_POWER_SUPPLY_ABNORMAL_LEVEL1_FAULT", desc = "市电异常一级故障【BSWSPowerSupplyAbnormalFlg、SbEMCR_PowerSupplyAbnormalLvl1FltFlg】" },
            [35] = { name = "ACIS_FIRE_ALARM_ACTIVATED_FAULT", desc = "消防火警启动异常【BSWSCmbstlGasFlg，BSWSExpprfFanFlg；SbACIS_FireAlarmActedFlt】" },
            [36] = { name = "ACIS_SPD_DC_SURGE_FAULT", desc = "中控柜直流SPD浪涌故障【BSWSDCSPDSrgFlg;SbACIS_DCSPDSrgFlt】" },
            [37] = { name = "ACIS_BAKEUP_POWER_SPD_FAULT", desc = "备电SPD1故障【BSWSBkupSpdSrgFlg】" },
            [38] = { name = "ACIS_EXTERNAL_EPO_FAULT", desc = "客户外部急停【BSWSExternalEPOFlg】" },
            [39] = { name = "THMC_TMS_LEVEL3_FAULT", desc = "水冷机三级故障【ScTMCR_TMSFltLevelState；SbTHMC_TMSLvl3Flt】" },
            [40] = { name = "EMCR_A_CORE_COMMUNICATION_FAULT", desc = "A核通讯故障【BSWSACoreCommFltFlg；SbEMCR_ACoreCommFltFlg】" },
            [41] = { name = "EMCR_ONERACK_TO_BANK_CAN_COMMUNICATION_LOST_FAULT", desc = "至少一个RBMS的CAN通讯丢失【SbEMCR_OneRackCanCommLostPreFltFlg；SbEMCR_OneRackCanCommLostFltFlg】" },
            [42] = { name = "EMCR_ALLRACK_TO_BANK_CAN_COMMUNICATION_LOST_FAULT", desc = "所有RBMS的CAN通讯丢失【SbEMCR_AllRackCanCommLostPreFltFlg；SbEMCR_AllRackCanCommLostFltFlg】" },
            [43] = { name = "ACIS_CONVERGENCE_FUSE_FAULT", desc = "汇流熔断器故障【BSWSCvrgFuseFlg;SbACIS_CvrgFuseFlt】" },
            [44] = { name = "EMCR_CONTROLCABINET_DEHUMIDIFIER_TO_BMS_COMM_LOST_FAULT", desc = "中控柜空调/除湿机通讯节点丢失故障【BSWControlCabinetDehumidifierMsgAvlFlg、SbEMCR_ControlCabinetDehumidifierComLostFltFlg】" },
            [45] = { name = "ACIS_CENTRAL_CONTROL_CABINET_SWITCH_FAULT", desc = "中控柜行程开关故障【BSWSCtrlCabSwthFlg；SbACIS_CtrlCabFlt】" },
            [46] = { name = "EMCR_FIREFIGHTING_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "消防通讯节点丢失故障【BSWSFirefightingMsgAvlFlg、SbEMCR_FirefightingComLostFltFlg】" },
            [47] = { name = "EMCR_POWER_SUPPLY_ABNORMAL_LEVEL3_FAULT", desc = "市电异常三级故障【BSWSPowerSupplyAbnormalFlg、SbEMCR_PowerSupplyAbnormalLvl3FltFlg】" },
            [48] = { name = "BCFR_HVBOX_BUSBARCAB_REVERSECON_FAULT", desc = "高压盒与汇流柜反接故障【ScBCFR_ReverConRackFailNbr，SbBCFR_ReverseConPreFltFlg；SbBCFR_ReverseConFlt】" },
        },
    },
    ["BBMS_A_Fault"] = {
        label = "BBMS_A_Fault (A核)",
        total_bytes = 25,
        bitmap_bytes = 25,
        bit_count = 200,
        source = "SystemConfiguration_BMS20A_BBMS.xlsm",
        entries = {
            [0] = { name = "EMCR_SSD_Fault", desc = "SSD故障【BSWSSSDLostFlg；SbEMCR_SSDLostFltFlg】" },
            [1] = { name = "EMCR_SD_Fault", desc = "SD故障【BSWSSDLostFlg；SbEMCR_SDLostFltFlg】" },
            [2] = { name = "EMCR_M_CORE_COMMUNICATION_FAULT", desc = "M核通讯故障【BSWSMCoreCommFltFlg；SbEMCR_MCoreCommFltFlg】" },
            [3] = { name = "EMCR_EMS_TO_BMS_COMMUNICATION_LOST_FAULT", desc = "EMS通讯节点丢失故障【BSWEMSMsgAvlFlg、SbEMCR_EMSCommLostFltFlg】" },
            [4] = { name = "EMCR_ONERACK_TO_BANK_LAN_COMMUNICATION_LOST_FAULT", desc = "至少一个RBMS的LAN通讯丢失【SbEMCR_OneRackLanCommLostPreFltFlg；SbEMCR_OneRackLanCommLostFltFlg】" },
            [5] = { name = "EMCR_ALLRACK_TO_BANK_LAN_COMMUNICATION_LOST_FAULT", desc = "所有RBMS的LAN通讯丢失【SbEMCR_AllRackLanCommLostPreFltFlg；SbEMCR_AllRackLanCommLostFltFlg】" },
            [6] = { name = "EMCR_ONERACK_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "至少一个RBMS通讯丢失【SbEMCR_OneRackCommLostPreFltFlg；SbEMCR_OneRackCommLostFltFlg】" },
            [7] = { name = "EMCR_ALLRACK_TO_BANK_COMMUNICATION_LOST_FAULT", desc = "所有RBMS通讯丢失【SbEMCR_AllRackCommLostPreFltFlg；SbEMCR_AllRackCommLostFltFlg】" },
        },
    },
}

bms20_fault_routes = {
    [5002] = {
        [0x0109] = "BBMS_A_Fault",
        [0x0213] = "BBMS_Fault_M",
    },
    [5003] = {
        [0x0329] = "RBMS_Fault",
    },
    [5004] = {
        [0x0329] = "RBMS_Fault",
    },
    [5005] = {
        [0x0329] = "RBMS_Fault",
    },
    [5006] = {
        [0x0329] = "RBMS_Fault",
    },
    [5007] = {
        [0x0329] = "RBMS_Fault",
    },
    [5008] = {
        [0x0329] = "RBMS_Fault",
    },
    [5009] = {
        [0x0329] = "RBMS_Fault",
    },
    [5010] = {
        [0x0329] = "RBMS_Fault",
    },
    [5011] = {
        [0x0329] = "RBMS_Fault",
    },
    [5012] = {
        [0x0329] = "RBMS_Fault",
    },
    [5013] = {
        [0x0329] = "RBMS_Fault",
    },
    [5014] = {
        [0x0329] = "RBMS_Fault",
    },
}

bms20_fault_wire_profile = {
    [0x0109] = "BBMS_A_Fault",
    [0x0213] = "BBMS_Fault_M",
    [0x0329] = "RBMS_Fault",
}

bms20_fault_wire_ids = {
    [0x0109] = true,
    [0x0213] = true,
    [0x0329] = true,
}

function bms20_is_fault_wire_id(wire_id)
    return bms20_fault_wire_ids ~= nil and bms20_fault_wire_ids[wire_id] == true
end

function bms20_fault_route_key(service_port, cmd_group, cmd_id)
    local cmd_key = bit.bor(bit.lshift(cmd_group, 8), cmd_id)
    if service_port ~= nil and bms20_fault_routes[service_port] ~= nil then
        local routed = bms20_fault_routes[service_port][cmd_key]
        if routed ~= nil then
            return routed
        end
    end
    if bms20_fault_wire_profile ~= nil then
        return bms20_fault_wire_profile[cmd_key]
    end
    return nil
end

function bms20_fault_display_name(service_port, cmd_group, cmd_id, msg_name)
    local profile_key = bms20_fault_route_key(service_port, cmd_group, cmd_id)
    if profile_key ~= nil and bms20_fault_profiles[profile_key] ~= nil then
        return bms20_fault_profiles[profile_key].label
    end
    return msg_name
end
