-- Auto-generated payload defs for ParaThr_SOX
-- Regenerate: python3 gen_payload_defs.py --message ParaThr_SOX

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["ParaThr_SOX"] = {
    total_bytes = 36,
    signals = {
        {
            name = "CcSOCA_SOCOverLowLvl1EnaThdValPct",
            desc = "SOCLowLvl1AssertThd SOC低一级报警阈值",
            start_bit = 0,
            bit_len = 32,
            res = 0.001953125,
            off = 0,
            byte_hint = "1-4",
        },
        {
            name = "CcSOCA_SOCOverLowLvl1RecThdValPct",
            desc = "SOCLowLvl1DeassertThd SOC低一级恢复阈值",
            start_bit = 32,
            bit_len = 32,
            res = 0.001953125,
            off = 0,
            byte_hint = "5-8",
        },
        {
            name = "CcSOHA_SOHCOverLowLvl1EnaThdValPct",
            desc = "SOHLowLvl1AssertThd SOH低一级报警阈值",
            start_bit = 64,
            bit_len = 16,
            res = 0.0078125,
            off = 0,
            byte_hint = "9-10",
        },
        {
            name = "CcSOHA_SOHCOverLowLvl2EnaThdValPct",
            desc = "SOHLowLvl2AssertThd SOH低二级报警阈值",
            start_bit = 80,
            bit_len = 16,
            res = 0.0078125,
            off = 0,
            byte_hint = "11-12",
        },
        {
            name = "CcSOHA_SOHCOverLowLvl3EnaThdValPct",
            desc = "SOHLowLvl3AssertThd SOH低三级报警阈值",
            start_bit = 96,
            bit_len = 16,
            res = 0.0078125,
            off = 0,
            byte_hint = "13-14",
        },
        {
            name = "CcSOCA_SOCDiffOverHighEnaThdValPct",
            desc = "SOCDiffTooBigLvl1AssertThd SOC差异过大报警阈值",
            start_bit = 112,
            bit_len = 32,
            res = 0.001953125,
            off = 0,
            byte_hint = "15-18",
        },
        {
            name = "CcSOCA_SOCDiffOverHighRecThdValPct",
            desc = "SOCDiffTooBigLvl1DeassertThd SOC差异过大恢复阈值",
            start_bit = 144,
            bit_len = 32,
            res = 0.001953125,
            off = 0,
            byte_hint = "19-22",
        },
        {
            name = "CcCBCC_CellSelfDischOverHighLvl1EnaThdValPct",
            desc = "SelfDischrgDiffTooBigLvl1AssertThd 自放电差异过大一级报警阈值",
            start_bit = 176,
            bit_len = 16,
            res = 0.001953125,
            off = 0,
            byte_hint = "23-24",
        },
        {
            name = "CcCBCC_CellSelfDischOverHighLvl2EnaThdValPct",
            desc = "SelfDischrgDiffTooBigLvl2AssertThd 自放电差异过大二级报警阈值",
            start_bit = 192,
            bit_len = 16,
            res = 0.001953125,
            off = 0,
            byte_hint = "25-26",
        },
        {
            name = "CcCBCC_CellSelfDischOverHighLvl2RecThdValPct",
            desc = "SelfDischrgDiffTooBigLvl2DeassertThd 自放电差异过大二级恢复阈值",
            start_bit = 208,
            bit_len = 16,
            res = 0.001953125,
            off = 0,
            byte_hint = "27-28",
        },
        {
            name = "CcCBCC_CellSelfDischOverHighLvl3EnaThdValPct",
            desc = "SelfDischrgDiffTooBigLvl3AssertThd 自放电差异过大三级报警阈值",
            start_bit = 224,
            bit_len = 16,
            res = 0.001953125,
            off = 0,
            byte_hint = "29-30",
        },
        {
            name = "CcCBCC_CellSelfDischOverHighLvl3RecThdValPct",
            desc = "SelfDischrgDiffTooBigLvl3DeassertThd 自放电差异过大三级恢复阈值",
            start_bit = 240,
            bit_len = 16,
            res = 0.001953125,
            off = 0,
            byte_hint = "31-32",
        },
        {
            name = "CcSOCA_OverChgFltEnaThdValPct",
            desc = "OverChgFltEnaThdValPct 过充故障判断阈值",
            start_bit = 256,
            bit_len = 32,
            res = 0.001953125,
            off = 0,
            byte_hint = "33-36",
        },
    },
}
