-- Auto-generated payload defs for ParaThr_RackI
-- Regenerate: python3 gen_payload_defs.py --message ParaThr_RackI

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["ParaThr_RackI"] = {
    total_bytes = 20,
    signals = {
        {
            name = "CcBTCD_RchaCurLvl1LimThdA",
            desc = "ChrgOverCurLvl1AssertThd 充电过流一级报警阈值",
            start_bit = 0,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "1-2",
        },
        {
            name = "CcBTCD_RchaCurLvl2LimThdA",
            desc = "ChrgOverCurLvl2AssertThd 充电过流二级报警阈值",
            start_bit = 16,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "3-4",
        },
        {
            name = "CcBTCD_RchaCurClrLvl2LimThdA",
            desc = "ChrgOverCurLvl2DeassertThd 充电过流二级恢复阈值",
            start_bit = 32,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "5-6",
        },
        {
            name = "CcBTCD_RchaCurLvl3LimThdA",
            desc = "ChrgOverCurLvl3AssertThd 充电过流三级报警阈值",
            start_bit = 48,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "7-8",
        },
        {
            name = "CcBTCD_RchaCurClrLvl3LimThdA",
            desc = "ChrgOverCurLvl3DeassertThd 充电过流三级恢复阈值",
            start_bit = 64,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "9-10",
        },
        {
            name = "CcBTCD_DchILimLvl1ThdA",
            desc = "DisChrgOverCurLvl1AssertThd 放电过流一级报警阈值",
            start_bit = 80,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "11-12",
        },
        {
            name = "CcBTCD_DchILimLvl2ThdA",
            desc = "DisChrgOverCurLvl2AssertThd 放电过流二级报警阈值",
            start_bit = 96,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "13-14",
        },
        {
            name = "CcBTCD_DchIClrLimLvl2ThdA",
            desc = "DisChrgOverCurLvl2DeassertThd 放电过流二级恢复阈值",
            start_bit = 112,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "15-16",
        },
        {
            name = "CcBTCD_DchILimLvl3ThdA",
            desc = "DisChrgOverCurLvl3AssertThd 放电过流三级报警阈值",
            start_bit = 128,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "17-18",
        },
        {
            name = "CcBTCD_DchIClrLimLvl3ThdA",
            desc = "DisChrgOverCurLvl3DeassertThd 放电过流三级恢复阈值",
            start_bit = 144,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "19-20",
        },
    },
}
