-- Auto-generated payload defs for RBMS_SumInfo
-- Regenerate: python3 gen_payload_defs.py --message RBMS_SumInfo

bms20_payload_defs = bms20_payload_defs or {}

bms20_payload_defs["RBMS_SumInfo"] = {
    total_bytes = 310,
    signals = {
        {
            name = "RBMS_St",
            desc = "Battery String Status 电池串工作状态",
            start_bit = 0,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "1",
        },
        {
            name = "RBMS_ChaSt",
            desc = "Rack Charging Status Rack充放电状态",
            start_bit = 8,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "2",
        },
        {
            name = "RBMS_SysOperSt",
            desc = "Rack Operating Status Rack运行状态",
            start_bit = 16,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "3",
        },
        {
            name = "RBMS_ConSt",
            desc = "Contactor Status 继电器/干接点状态",
            start_bit = 24,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "4-5",
        },
        {
            name = "RBMS_ConFail",
            desc = "HV Connect Fail Reason 高压连接失败原因",
            start_bit = 40,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "6-7",
        },
        {
            name = "RBMS_V",
            desc = "Battery String Voltage (V) 电池串电压 (V)",
            start_bit = 56,
            bit_len = 16,
            res = 0.5,
            off = 0,
            byte_hint = "8-9",
        },
        {
            name = "RBMS_DCBusV",
            desc = "DC Bus Voltage (V) 总线电压 (V)",
            start_bit = 72,
            bit_len = 16,
            res = 0.5,
            off = 0,
            byte_hint = "10-11",
        },
        {
            name = "RBMS_A_HighAccu",
            desc = "DC Bus Current (A) (High accu) 总线电流 (A) (高精度)",
            start_bit = 88,
            bit_len = 32,
            res = 0.001,
            off = -2000,
            byte_hint = "12-15",
        },
        {
            name = "RBMS_IsoR",
            desc = "Insulation Resistance (kOhm) 绝缘阻值 (kOhm)",
            start_bit = 120,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "16-17",
        },
        {
            name = "RBMS_HvBoxMaxTemp",
            desc = "Max HV Box Temperature (℃) 最高高压箱温度 (℃)",
            start_bit = 136,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "18-19",
            signed = true,
        },
        {
            name = "RBMS_HvBoxMinTemp",
            desc = "Min HV Box Temperature (℃) 最低高压箱温度 (℃)",
            start_bit = 152,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "20-21",
            signed = true,
        },
        {
            name = "Reserved3",
            desc = "Reserved3 预留占位3",
            start_bit = 168,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "22",
        },
        {
            name = "RBMS_LowPowSply",
            desc = "Low Power Supply Voltage (mV) 低压供电电压 (mV)",
            start_bit = 176,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "23-24",
        },
        {
            name = "RBMS_RlyCtrlSeqStState",
            desc = "Relay Control Status 继电器控制状态",
            start_bit = 192,
            bit_len = 4,
            res = 1,
            off = 0,
            byte_hint = "25",
        },
        {
            name = "RBMS_ReverConDetecOpenFlg",
            desc = "Rack Anti-Reversal Connection Detection Enable Flg 簇防反接检测功能使能标志位",
            start_bit = 196,
            bit_len = 1,
            res = 1,
            off = 0,
            byte_hint = "25",
        },
        {
            name = "Reserved",
            desc = "Reserved 预留占位",
            start_bit = 197,
            bit_len = 3,
            res = 1,
            off = 0,
            byte_hint = "25",
        },
        {
            name = "Reserved1",
            desc = "Reserved1 预留占位1",
            start_bit = 200,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "26",
        },
        {
            name = "RBMS_HisSleepTiWrMin",
            desc = "Rack History Sleep Time (min) 历史休眠时间 (min)",
            start_bit = 208,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "27-30",
        },
        {
            name = "RBMS_HisRunTiWrMin",
            desc = "Rack History Run Time (min) 历史运行时间 (min)",
            start_bit = 240,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "31-34",
        },
        {
            name = "RBMS_LstSleepDurTiMin",
            desc = "Last Power-down Sleep Time (min) 上次下电休眠时间 (min)",
            start_bit = 272,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "35-38",
        },
        {
            name = "RBMS_IDLearnCodeSt",
            desc = "Rack ID Learn Status Rack ID编码状态",
            start_bit = 304,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "39",
        },
        {
            name = "RBMS_IsoRPos",
            desc = "Positive to GND Insulation Resistance (kOhm) 正对地绝缘阻值 (kOhm)",
            start_bit = 312,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "40-41",
        },
        {
            name = "RBMS_IsoRNeg",
            desc = "Negative to GND Insulation Resistance (kOhm) 负对地绝缘阻值 (kOhm)",
            start_bit = 328,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "42-43",
        },
        {
            name = "RBMS_CmdInhibitFlg",
            desc = "Insulation Disable Flag 绝缘禁止标志位",
            start_bit = 344,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "44",
        },
        {
            name = "RBMS_IslnHvVldNbr",
            desc = "Insulation High Voltage Validity Status 绝缘高压有效性状态",
            start_bit = 352,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "45",
        },
        {
            name = "RBMS_IslnInhibitNbr",
            desc = "Insulation Prohibition Reason 绝缘禁止原因",
            start_bit = 360,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "46",
        },
        {
            name = "RBMS_CellTMUXFaiIDNbr",
            desc = "Temp Sampling MUX Fail Position 温度采样MUX失效位置",
            start_bit = 368,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "47-110",
            array_count = 64,
        },
        {
            name = "RBMS_SoC",
            desc = "Rack SOC (%) Rack SOC（%）",
            start_bit = 880,
            bit_len = 8,
            res = 0.5,
            off = 0,
            byte_hint = "111",
        },
        {
            name = "RBMS_SoH",
            desc = "Rack SOH (%) Rack SOH（%）",
            start_bit = 888,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "112",
        },
        {
            name = "RBMS_SoEC",
            desc = "Rack SOE for Charge (kWh) Rack可充能量 (kWh)",
            start_bit = 896,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "113-114",
        },
        {
            name = "RBMS_SoED",
            desc = "Rack SOE for Discharge (kWh) Rack可放能量 (kWh)",
            start_bit = 912,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "115-116",
        },
        {
            name = "RBMS_SoFPulseChrgCurr",
            desc = "Pulse Charge Curr Limit (A) 脉冲充电电流限制 (A)",
            start_bit = 928,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "117-118",
        },
        {
            name = "RBMS_SoFPulseDisChrgCurr",
            desc = "Pulse Discharge Curr Limit (A) 脉冲放电电流限制 (A)",
            start_bit = 944,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "119-120",
        },
        {
            name = "RBMS_SoFPulseChrgPwr",
            desc = "Pulse Charge Power Limit (kW) 脉冲充电功率限制 (kW)",
            start_bit = 960,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "121-122",
        },
        {
            name = "RBMS_SoFPulseDisChrgPwr",
            desc = "Pulse Discharge Power Limit (kW) 脉冲放电功率限制 (kW)",
            start_bit = 976,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "123-124",
        },
        {
            name = "RBMS_SoFContChrgCurr",
            desc = "Const Charge Curr Limit (A) 持续充电电流限制 (A)",
            start_bit = 992,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "125-126",
        },
        {
            name = "RBMS_SoFContDisChrgCurr",
            desc = "Const Discharge Curr Limit (A) 持续放电电流限制 (A)",
            start_bit = 1008,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "127-128",
        },
        {
            name = "RBMS_SoFContChrgPwr",
            desc = "Const Charge Power Limit (kW) 持续充电功率限制 (kW)",
            start_bit = 1024,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "129-130",
        },
        {
            name = "RBMS_SoFContDisChrgPwr",
            desc = "Const Discharge Power Limit (kW) 持续放电功率限制 (kW)",
            start_bit = 1040,
            bit_len = 16,
            res = 0.125,
            off = 0,
            byte_hint = "131-132",
        },
        {
            name = "RBMS_CellVMax",
            desc = "Max Cell Voltage (mV) 最大电芯电压 (mV)",
            start_bit = 1056,
            bit_len = 14,
            res = 1,
            off = 0,
            byte_hint = "133-134",
        },
        {
            name = "RBMS_CellVMaxPstn",
            desc = "Max Cell Voltage Position 最大电芯电压位置",
            start_bit = 1070,
            bit_len = 11,
            res = 1,
            off = 0,
            byte_hint = "134-136",
        },
        {
            name = "RBMS_CellVMin",
            desc = "Min Cell Voltage (mV) 最小电芯电压 (mV)",
            start_bit = 1081,
            bit_len = 14,
            res = 1,
            off = 0,
            byte_hint = "136-137",
        },
        {
            name = "RBMS_CellVMinPstn",
            desc = "Min Cell Voltage Position 最小电芯电压位置",
            start_bit = 1095,
            bit_len = 11,
            res = 1,
            off = 0,
            byte_hint = "137-139",
        },
        {
            name = "RBMS_CellVAvg",
            desc = "Average Cell Voltage (mV) 平均电芯电压 (mV)",
            start_bit = 1106,
            bit_len = 14,
            res = 1,
            off = 0,
            byte_hint = "139-140",
        },
        {
            name = "RBMS_ModTmpMax",
            desc = "Max Module Temp (℃) 最高电芯温度 (℃)",
            start_bit = 1120,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "141-142",
            signed = true,
        },
        {
            name = "Reserved4",
            desc = "Reserved4 预留占位4",
            start_bit = 1136,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "143",
        },
        {
            name = "RBMS_ModTmpMin",
            desc = "Min Cell Temp (℃) 最低电芯温度 (℃)",
            start_bit = 1144,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "144-145",
            signed = true,
        },
        {
            name = "RBMS_MCURstRsnFltNbr",
            desc = "Fault Causes Leading to MCU Reset 导致MCU复位的故障原因",
            start_bit = 1160,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "146",
        },
        {
            name = "RBMS_ModTmpAvg",
            desc = "Average Cell Temp (℃) 平均电芯温度 (℃)",
            start_bit = 1168,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "147-148",
            signed = true,
        },
        {
            name = "RBMS_MaxPoleTDegC",
            desc = "Max Pole Temp (℃) 最高极柱温度 (℃)",
            start_bit = 1184,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "149-150",
            signed = true,
        },
        {
            name = "RBMS_MaxPoleTIdxNbr",
            desc = "Max Pole Temp Position 最高极柱温度位置",
            start_bit = 1200,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "151",
        },
        {
            name = "RBMS_MinPoleTDegC",
            desc = "Min Pole Temp (℃) 最低极柱温度 (℃)",
            start_bit = 1208,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "152-153",
            signed = true,
        },
        {
            name = "RBMS_MinPoleTIdxNbr",
            desc = "Min Pole Temp Position 最低极柱温度位置",
            start_bit = 1224,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "154",
        },
        {
            name = "RBMS_MaxPoleTMdulIdxNbr",
            desc = "Max Pole Temp Module Position 最高极柱温度模组位置",
            start_bit = 1232,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "155",
        },
        {
            name = "RBMS_MinPoleTMdulIdxNbr",
            desc = "Min Pole Temp Module Position 最低极柱温度模组位置",
            start_bit = 1240,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "156",
        },
        {
            name = "RBMS_AvgPoleTDegC",
            desc = "Average Pole Temp (℃) 平均极柱温度 (℃)",
            start_bit = 1248,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "157-158",
            signed = true,
        },
        {
            name = "RBMS_CommType",
            desc = "Communication Type 通讯类型",
            start_bit = 1264,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "159",
        },
        {
            name = "RBMS_StrCtrlHb",
            desc = "Rack BMS Heartbeat Rack BMS心跳信号",
            start_bit = 1272,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "160-161",
        },
        {
            name = "RBMS_ResChAvlCapAh",
            desc = "Remaining Charge Cap (Ah) 可充容量 (Ah)",
            start_bit = 1288,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "162-163",
        },
        {
            name = "RBMS_ResDischAvlCapAh",
            desc = "Remaining Discharge Cap (Ah) 可放容量 (Ah)",
            start_bit = 1304,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "164-165",
        },
        {
            name = "RBMS_LstFullChCapAh",
            desc = "Rack Last Full-Charge Cap (Ah) 最近一次簇满充容量 (Ah)",
            start_bit = 1320,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "166-167",
        },
        {
            name = "RBMS_LstFullDischCapAh",
            desc = "Rack Last Full-Discharge Cap (Ah) 最近一次簇满放容量 (Ah)",
            start_bit = 1336,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "168-169",
        },
        {
            name = "RBMS_CycNbr",
            desc = "Full Equiv Ch-Disch Cycles 等效完整充放电循环次数",
            start_bit = 1352,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "170-171",
        },
        {
            name = "RBMS_MaxPoleTMdulInnerIdxNbr",
            desc = "Max Pole Temp Module Inner Position 最高极柱温度模组内位置",
            start_bit = 1368,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "172",
        },
        {
            name = "RBMS_MinPoleTMdulInnerIdxNbr",
            desc = "Min Pole Temp Module Inner Position 最低极柱温度模组内位置",
            start_bit = 1376,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "173",
        },
        {
            name = "RBMS_AFEChipTmpMax",
            desc = "Max AFE Chip Temperature (℃) 最高AFE芯片温度 (℃)",
            start_bit = 1384,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "174",
        },
        {
            name = "RBMS_AFEChipTmpMin",
            desc = "Min AFE Temperature (℃) 最低AFE温度 (℃)",
            start_bit = 1392,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "175",
        },
        {
            name = "RBMS_MCURstRsnNbr",
            desc = "MCU Reset Source MCU复位源",
            start_bit = 1400,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "176-177",
        },
        {
            name = "RBMS_GenlVldFlg",
            desc = "RBMS Sampling Validity Flag RBMS采样有效性标志",
            start_bit = 1416,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "178-179",
        },
        {
            name = "RBMS_IslnFinalBatV",
            desc = "Total Insulation Voltage (V) 绝缘总压 (V)",
            start_bit = 1432,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "180-181",
        },
        {
            name = "RBMS_IslnFinalPosV",
            desc = "Insulation Positive to GND Voltage (V) 绝缘正对地电压 (V)",
            start_bit = 1448,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "182-183",
        },
        {
            name = "RBMS_IslnFinalNegV",
            desc = "Insulation Negative to GND Voltage (V) 绝缘负对地电压 (V)",
            start_bit = 1464,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "184-185",
        },
        {
            name = "RBMS_IslnMeastStState",
            desc = "Insulation Measure Status 绝缘测量状态",
            start_bit = 1480,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "186-187",
        },
        {
            name = "RBMS_LstChEkWh",
            desc = "Rack Last Charge Energy (kWh) 最近一次簇充电能量 (kWh)",
            start_bit = 1496,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "188-189",
        },
        {
            name = "RBMS_LstDchEkWh",
            desc = "Rack Last Discharge Energy (kWh) 最近一次簇放电能量 (kWh)",
            start_bit = 1512,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "190-191",
        },
        {
            name = "RBMS_BalBdTmpMax",
            desc = "Max Balancing Board Temp (℃) 最高均衡板温 (℃)",
            start_bit = 1528,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "192-193",
            signed = true,
        },
        {
            name = "RBMS_RmngCellBalTiMax",
            desc = "Max Balancing Remain Time (min) 最大剩余均衡时间 (min)",
            start_bit = 1544,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "194-195",
        },
        {
            name = "RBMS_RealSysSOHC",
            desc = "Rack Real SOH (%) Rack真实SOH (%)",
            start_bit = 1560,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "196-197",
        },
        {
            name = "RBMS_RealSysCapAh",
            desc = "Rack Max Available Capacity (Ah) 电池簇最大可用容量 (Ah)",
            start_bit = 1576,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "198-199",
        },
        {
            name = "RBMS_RealCellCapAh",
            desc = "Min Cell Real Capacity (Ah) 最小电芯真实容量 (Ah)",
            start_bit = 1592,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "200-201",
        },
        {
            name = "RBMS_SysMaxSOC",
            desc = "RBMS Max SOC (%) RBMS最大SOC (%)",
            start_bit = 1608,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "202-203",
        },
        {
            name = "RBMS_SysMinSOC",
            desc = "RBMS Min SOC (%) RBMS最小SOC (%)",
            start_bit = 1624,
            bit_len = 16,
            res = 0.01,
            off = 0,
            byte_hint = "204-205",
        },
        {
            name = "RBMS_RealSysSOCPct",
            desc = "Rack Real SOC (%) Rack真实SOC (%)",
            start_bit = 1640,
            bit_len = 32,
            res = 0.01,
            off = 0,
            byte_hint = "206-209",
        },
        {
            name = "RBMS_AccuDisChrgAh2",
            desc = "Accu Discharge Cap (Ah) 累计放电容量 (Ah)",
            start_bit = 1672,
            bit_len = 32,
            res = 0.0625,
            off = 0,
            byte_hint = "210-213",
        },
        {
            name = "RBMS_AccuDisChrgkWh2",
            desc = "Accu Discharge Eng (kWh) 累计放电能量 (kWh)",
            start_bit = 1704,
            bit_len = 32,
            res = 0.0625,
            off = 0,
            byte_hint = "214-217",
        },
        {
            name = "RBMS_AccuChrgAh2",
            desc = "Accu Charge Cap (Ah) 累计充电容量 (Ah)",
            start_bit = 1736,
            bit_len = 32,
            res = 0.0625,
            off = 0,
            byte_hint = "218-221",
        },
        {
            name = "RBMS_AccuChrgkWh2",
            desc = "Accu Charge Eng (kWh) 累计充电能量 (kWh)",
            start_bit = 1768,
            bit_len = 32,
            res = 0.0625,
            off = 0,
            byte_hint = "222-225",
        },
        {
            name = "RBMS_BMSMaxFltLevel",
            desc = "Rack Fault Level Rack故障等级",
            start_bit = 1800,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "226",
        },
        {
            name = "RBMS_MaxCellVMdulTDegC",
            desc = "Max Voltage Cell Temp (℃) 最大电压电芯对应温度 (℃)",
            start_bit = 1808,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "227-228",
            signed = true,
        },
        {
            name = "RBMS_MinCellVMdulTDegC",
            desc = "Min Voltage Cell Temp (℃) 最小电压电芯对应温度 (℃)",
            start_bit = 1824,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "229-230",
            signed = true,
        },
        {
            name = "RBMS_MaxCellVMdulTVldFlg",
            desc = "Max Voltage Cell Temp Validity 最大电压电芯温度有效性",
            start_bit = 1840,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "231",
        },
        {
            name = "RBMS_MinCellVMdulTVldFlg",
            desc = "Min Voltage Cell Temp Validity 最小电压电芯温度有效性",
            start_bit = 1848,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "232",
        },
        {
            name = "RBMS_A",
            desc = "DC Bus Current (A) 总线电流 (A)",
            start_bit = 1856,
            bit_len = 16,
            res = 0.125,
            off = -2000,
            byte_hint = "233-234",
            signed = true,
        },
        {
            name = "RBMS_A1",
            desc = "Rack Current of Sensor 1 (A) 传感器1的簇电流 (A)",
            start_bit = 1872,
            bit_len = 16,
            res = 0.125,
            off = -2000,
            byte_hint = "235-236",
            signed = true,
        },
        {
            name = "RBMS_A2",
            desc = "Rack Current of Sensor 2 (A) 传感器2的簇电流 (A)",
            start_bit = 1888,
            bit_len = 16,
            res = 0.125,
            off = -2000,
            byte_hint = "237-238",
            signed = true,
        },
        {
            name = "RBMS_BalBdTmpMin",
            desc = "Min Balancing Board Temp (℃) 最低均衡板温 (℃)",
            start_bit = 1904,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "239-240",
            signed = true,
        },
        {
            name = "RBMS_PreChrgRT",
            desc = "Precharge Resistor Temp (℃) 预充电阻温度 (℃)",
            start_bit = 1920,
            bit_len = 8,
            res = 1,
            off = -40,
            byte_hint = "241",
        },
        {
            name = "RBMS_RlyCtrlCmd",
            desc = "Relay Control Cmd 继电器控制命令",
            start_bit = 1928,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "242",
        },
        {
            name = "RBMS_FaultEvt",
            desc = "Fault Event 故障信息",
            start_bit = 1936,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "243-246",
        },
        {
            name = "RBMS_AttachState",
            desc = "Attachment Status 附件状态",
            start_bit = 1968,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "247",
        },
        {
            name = "Reserved2",
            desc = "Reserved2 预留占位2",
            start_bit = 1976,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "248",
        },
        {
            name = "RBMS_MaxCellVMdulIdxNbr",
            desc = "Max Cell Voltage Module Position 最高电芯电压模组位置",
            start_bit = 1984,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "249-250",
        },
        {
            name = "RBMS_MinCellVMdulIdxNbr",
            desc = "Min Cell Voltage Module Position 最低电芯电压模组位置",
            start_bit = 2000,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "251-252",
        },
        {
            name = "RBMS_MaxTMdulIdxNbr",
            desc = "Max Cell Temp Module Position 最高电芯温度模组位置",
            start_bit = 2016,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "253-254",
        },
        {
            name = "RBMS_MinTMdulIdxNbr",
            desc = "Min Cell Temp Module Position 最低电芯温度模组位置",
            start_bit = 2032,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "255-256",
        },
        {
            name = "RBMS_MaxCellVMdulInnerIdxNbr",
            desc = "Max Cell Voltage Module Inner Position 最高电芯电压模组内位置",
            start_bit = 2048,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "257-258",
        },
        {
            name = "RBMS_MinCellVMdulInnerIdxNbr",
            desc = "Min Cell Voltage Module Inner Position 最低电芯电压模组内位置",
            start_bit = 2064,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "259-260",
        },
        {
            name = "RBMS_MaxTMdulInnerIdxNbr",
            desc = "Max Cell Temp Module Inner Position 最高电芯温度模组内位置",
            start_bit = 2080,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "261-262",
        },
        {
            name = "RBMS_MinTMdulInnerIdxNbr",
            desc = "Min Cell Temp Module Inner Position 最低电芯温度模组内位置",
            start_bit = 2096,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "263-264",
        },
        {
            name = "RBMS_DaisyChain1LastNode",
            desc = "AFE Daisy Chain Master Chain Nodes AFE菊花链主链节点数",
            start_bit = 2112,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "265",
        },
        {
            name = "RBMS_DaisyChain2LastNode",
            desc = "AFE Daisy Chain Slave Chain Nodes AFE菊花链副链节点数",
            start_bit = 2120,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "266",
        },
        {
            name = "RBMS_ModTmpMaxPstn",
            desc = "Max Cell Temp Position 最高电芯温度位置",
            start_bit = 2128,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "267-268",
        },
        {
            name = "RBMS_ModTmpMinPstn",
            desc = "Min Module Temp Position 最低电芯温度位置",
            start_bit = 2144,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "269-270",
        },
        {
            name = "RBMS_AccuDisChrgAh",
            desc = "Accu Discharge Cap (Ah) (Low accu) 累计放电容量 (Ah) (低精度)",
            start_bit = 2160,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "271-274",
        },
        {
            name = "RBMS_AccuDisChrgkWh",
            desc = "Accu Discharge Eng (kWh) (Low accu) 累计放电能量 (kWh) (低精度)",
            start_bit = 2192,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "275-278",
        },
        {
            name = "RBMS_AccuChrgAh",
            desc = "Accu Charge Cap (Ah) (Low accu) 累计充电容量 (Ah) (低精度)",
            start_bit = 2224,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "279-282",
        },
        {
            name = "RBMS_AccuChrgkWh",
            desc = "Accu Charge Eng (kWh) (Low accu) 累计充电能量 (kWh) (低精度)",
            start_bit = 2256,
            bit_len = 32,
            res = 1,
            off = 0,
            byte_hint = "283-286",
        },
        {
            name = "RBMS_LstChCapAh",
            desc = "Rack Last Charge Cap (Ah) 最近一次簇充电容量 (Ah)",
            start_bit = 2288,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "287-288",
        },
        {
            name = "RBMS_LstDchCapAh",
            desc = "Rack Last Discharge Cap (Ah) 最近一次簇放电容量 (Ah)",
            start_bit = 2304,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "289-290",
        },
        {
            name = "RBMS_FltSOPDischCoeffPct",
            desc = "Fault-based Discharge Power Limit Coefficient (%) 基于故障的放电功率限制系数",
            start_bit = 2320,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "291",
        },
        {
            name = "RBMS_FltSOPChCoeffPct",
            desc = "Fault-based Charge Power Limit Coefficient (%) 基于故障的充电功率限制系数",
            start_bit = 2328,
            bit_len = 8,
            res = 1,
            off = 0,
            byte_hint = "292",
        },
        {
            name = "RBMS_CurrSnsrPowSplyVoltmV",
            desc = "Current Sensor Power Supply Volt (mV) 电流传感器供电电压 (mV)",
            start_bit = 2336,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "293-294",
        },
        {
            name = "RBMS_CtlBoxT0DegC",
            desc = "HV Box Temperature0 (℃) 高压箱温度T0 (℃)",
            start_bit = 2352,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "295-296",
            signed = true,
        },
        {
            name = "RBMS_CtlBoxT1DegC",
            desc = "HV Box Temperature1 (℃) 高压箱温度T1 (℃)",
            start_bit = 2368,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "297-298",
            signed = true,
        },
        {
            name = "RBMS_CtlBoxT2DegC",
            desc = "HV Box Temperature2 (℃) 高压箱温度T2 (℃)",
            start_bit = 2384,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "299-300",
            signed = true,
        },
        {
            name = "RBMS_CtlBoxT3DegC",
            desc = "HV Box Temperature3 (℃) 高压箱温度T3 (℃)",
            start_bit = 2400,
            bit_len = 16,
            res = 0.1,
            off = -40,
            byte_hint = "301-302",
            signed = true,
        },
        {
            name = "RBMS_PCSChVoltLim",
            desc = "Charge Voltage Limit to PCS (V) 发送至PCS的充电限制电压 (V)",
            start_bit = 2416,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "303-304",
        },
        {
            name = "RBMS_PCSDchVoltLim",
            desc = "Discharge Voltage Limit to PCS 发送至PCS的放电限制电压 (V)",
            start_bit = 2432,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "305-306",
        },
        {
            name = "RBMS_PCSSOP",
            desc = "SOP to PCS (kW) 发送至PCS的SOP (kW)",
            start_bit = 2448,
            bit_len = 16,
            res = 0.1,
            off = 0,
            byte_hint = "307-308",
        },
        {
            name = "RBMS_PCSBMSSt",
            desc = "BMS Status to PCS 发送至PCS的BMS状态",
            start_bit = 2464,
            bit_len = 16,
            res = 1,
            off = 0,
            byte_hint = "309-310",
        },
    },
}
